import test from 'node:test';import assert from 'node:assert/strict';import {calculateApBillTotals,evaluateApInvoice,learnedClassificationSuggestion,AP_INVOICE_CLASSIFICATIONS} from '../src/apInvoiceEvaluation.js';
test('AP totals round and include tax and freight',()=>{const r=calculateApBillTotals([{qty:2,unitCost:125.5,discountAmount:1},{qty:3,unitCost:10,discountAmount:0}],{taxTotal:15,freight:5});assert.deepEqual([r.subtotal,r.discountTotal,r.netLines,r.invoiceTotal],[281,1,280,300]);assert.equal(r.lines[0].amount,250);});
test('three way auto approves inside percentage and dollar limits',()=>{const r=evaluateApInvoice({vendor:{id:'V1'},invoice:{invoiceNumber:'1',currency:'USD',date:'2026-07-01'},lines:[{qty:1,unitCost:10080,poNumber:'PO1'}],purchaseOrder:{vendorId:'V1',currency:'USD',status:'Open',total:10000},receipts:[{}]});assert.equal(r.approvalRequirement,'Auto Approved');assert.equal(r.approvalRuleId,'AP-3WAY-001');});
test('absolute variance overrides passing percentage',()=>{const r=evaluateApInvoice({vendor:{id:'V1'},invoice:{invoiceNumber:'2',currency:'USD',date:'2026-07-01'},lines:[{qty:1,unitCost:10150,poNumber:'PO1'}],purchaseOrder:{vendorId:'V1',currency:'USD',status:'Open',total:10000},receipts:[{}]});assert.equal(r.variances.totalPercent,1.5);assert.equal(r.approvalRequirement,'Exception Review');});
test('missing receipt blocks three way auto approval',()=>{const r=evaluateApInvoice({vendor:{id:'V1'},invoice:{invoiceNumber:'3',date:'2026-07-01'},lines:[{qty:1,unitCost:100,poNumber:'PO1'}],purchaseOrder:{vendorId:'V1',status:'Open',total:100},receipts:[]});assert.equal(r.classification,AP_INVOICE_CLASSIFICATIONS[0]);assert.equal(r.approvalRequirement,'Exception Review');});
test('recurring classification remains while failed profile requires exception review',()=>{const r=evaluateApInvoice({vendor:{id:'V1'},invoice:{invoiceClassification:'Recurring Utility Invoice',branch:'MAIN'},lines:[{qty:1,unitCost:200,expenseAccount:'UTIL'}],recurringProfile:{active:true,classification:'Recurring Utility Invoice',maximumInvoiceAmount:100,approvedBranches:['MAIN'],approvedAccounts:['UTIL']}});assert.equal(r.classification,'Recurring Utility Invoice');assert.equal(r.approvalRequirement,'Exception Review');});
test('duplicates always block auto approval',()=>{const r=evaluateApInvoice({vendor:{id:'V1'},invoice:{invoiceNumber:'4'},lines:[{qty:1,unitCost:100,poNumber:'P'}],purchaseOrder:{vendorId:'V1',status:'Open',total:100},receipts:[{}],duplicateResults:[{}]});assert.equal(r.approvalRequirement,'Exception Review');});
test('learning requires five corrections and 90 percent consistency without auto approval',()=>{const rows=Array.from({length:5},()=>({vendorId:'V1',selectedClassification:'Recurring Utility Invoice'}));const r=learnedClassificationSuggestion(rows,'V1');assert.equal(r.classification,'Recurring Utility Invoice');assert.equal(r.canAutoApprove,false);assert.match(r.proposedRuleStatus,/Pending/);});

test('negative AP line values are rejected',()=>assert.throws(()=>calculateApBillTotals([{qty:-1,unitCost:10}]),/non-negative/));
