import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { COOKIE_NAME, FileSecurityStore, SecurityError, SecurityService, securityHeaders } from '../src/security.js';

const bootstrapKeys=['NODE_ENV','ALLOW_PRODUCTION_BOOTSTRAP','BOOTSTRAP_ADMIN_EMAIL','BOOTSTRAP_ADMIN_PASSWORD'];
async function withBootstrapEnv(values,run) {
  const saved=Object.fromEntries(bootstrapKeys.map(key=>[key,process.env[key]]));
  for(const key of bootstrapKeys) delete process.env[key];
  Object.assign(process.env,values);
  try { return await run(); }
  finally { for(const key of bootstrapKeys) saved[key]===undefined?delete process.env[key]:process.env[key]=saved[key]; }
}
async function bootstrapFixture(values) {
  const root=await mkdtemp(path.join(os.tmpdir(),'erp-bootstrap-'));
  const store=new FileSecurityStore(root);
  const service=new SecurityService({store,appOrigin:'https://erp.example.invalid'});
  return {root,store,service,init:()=>withBootstrapEnv(values,()=>service.init())};
}

async function fixture() {
  const root=await mkdtemp(path.join(os.tmpdir(),'erp-security-'));
  const store=new FileSecurityStore(root); await store.init();
  const user={id:'00000000-0000-4000-8000-000000000001',email:'security@example.invalid',name:'Security Test',roles:['Admin'],active:true,companies:['*'],branches:['*'],departments:['*']}; store.users.push(user); await store.saveUsers();
  const service=new SecurityService({store,appOrigin:'https://erp.example.invalid'});
  return {service,store,user,req:{headers:{'user-agent':'security-test'},socket:{remoteAddress:'127.0.0.1'}}};
}
test('session token is a 256-bit opaque value and only its hash is stored',async()=>{const {service,store,user,req}=await fixture();const {token}=await service.createSession(user,req);assert.match(token,/^[A-Za-z0-9_-]{43}$/);assert.equal(store.sessions[0].tokenHash.length,64);assert.ok(!JSON.stringify(store.sessions).includes(token));});
test('legacy user-id session cookie is rejected',async()=>{const {service,req}=await fixture();req.headers.cookie='erp_session=00000000-0000-4000-8000-000000000001';assert.equal(await service.authenticate(req),null);});
test('unknown opaque session is rejected',async()=>{const {service,req}=await fixture();req.headers.cookie=`${COOKIE_NAME}=${Buffer.alloc(32,4).toString('base64url')}`;assert.equal(await service.authenticate(req),null);});
test('expired session is rejected',async()=>{const {service,store,user,req}=await fixture();const {token}=await service.createSession(user,req);store.sessions[0].idleExpiresAt=new Date(0).toISOString();req.headers.cookie=`${COOKIE_NAME}=${token}`;assert.equal(await service.authenticate(req),null);});
test('revoked session is rejected',async()=>{const {service,store,user,req}=await fixture();const {token,record}=await service.createSession(user,req);await service.revoke(record);req.headers.cookie=`${COOKIE_NAME}=${token}`;assert.equal(store.sessions[0].revokedAt!==null,true);assert.equal(await service.authenticate(req),null);});
test('deactivated user session is rejected and revoked',async()=>{const {service,store,user,req}=await fixture();const {token}=await service.createSession(user,req);user.active=false;await store.saveUsers();req.headers.cookie=`${COOKIE_NAME}=${token}`;assert.equal(await service.authenticate(req),null);assert.ok(store.sessions[0].revokedAt);});
test('session cookie uses required attributes',async()=>{const {service}=await fixture();const cookie=service.cookie('token');assert.match(cookie,/^__Host-erp_session=/);for(const attribute of ['Secure','HttpOnly','SameSite=Strict','Path=/'])assert.ok(cookie.includes(attribute));assert.ok(!cookie.includes('Domain='));});
test('CSRF rejects missing token and wrong origin',async()=>{const {service,user,req}=await fixture();const {record}=await service.createSession(user,req);req.auth={user,session:record};assert.throws(()=>service.verifyCsrf(req),SecurityError);req.headers.origin='https://attacker.invalid';req.headers['x-csrf-token']=Buffer.alloc(32,2).toString('base64url');assert.throws(()=>service.verifyCsrf(req),SecurityError);});
test('valid CSRF token and origin pass',async()=>{const {service,user,req}=await fixture();const {record}=await service.createSession(user,req);req.auth={user,session:record};const token=await service.csrf(req);req.headers.origin='https://erp.example.invalid';req.headers['x-csrf-token']=token;assert.doesNotThrow(()=>service.verifyCsrf(req));});
test('permissions have allowed and denied outcomes',async()=>{const {service,user,req}=await fixture();req.auth={user,session:{}};assert.doesNotThrow(()=>service.requirePermission(req,'AP_BILL_POST'));user.roles=['AP Clerk'];assert.throws(()=>service.requirePermission(req,'AP_BILL_POST'),e=>e.statusCode===403);assert.doesNotThrow(()=>service.requirePermission(req,'AP_BILL_CREATE'));});
test('security headers are centralized and do not enable wildcard CORS',()=>{const headers=new Map(),res={setHeader:(key,value)=>headers.set(key,value)};securityHeaders({url:'/api/ap/documents',headers:{}},res);for(const name of ['Content-Security-Policy','Strict-Transport-Security','X-Content-Type-Options','Referrer-Policy','Permissions-Policy','Cross-Origin-Opener-Policy','Cross-Origin-Resource-Policy','Cache-Control'])assert.ok(headers.has(name));assert.notEqual(headers.get('Access-Control-Allow-Origin'),'*');});
test('audit log is append-only JSONL and excludes tokens',async()=>{const {service,store,req}=await fixture();req.requestId='00000000-0000-4000-8000-000000000002';await service.audit(req,'LOGIN_FAILURE','denied',{reason:'Invalid credentials'});const contents=await readFile(store.auditPath,'utf8');assert.equal(JSON.parse(contents).action,'LOGIN_FAILURE');assert.ok(!contents.includes('csrfToken'));});
test('sixth login attempt is rate limited',async()=>{const {service}=await fixture();for(let i=0;i<5;i++)service.failedLogin('account|ip');assert.throws(()=>service.limitLogin('account|ip'),e=>e.statusCode===429);});
test('concurrent login/session writes remain ordered, valid, and leave no temporary files',async()=>{const {service,store,user,req}=await fixture();await Promise.all(Array.from({length:30},()=>service.createSession(user,req)));const saved=JSON.parse(await readFile(store.sessionPath,'utf8'));assert.equal(saved.length,30);assert.equal(new Set(saved.map(s=>s.id)).size,30);assert.deepEqual((await readdir(store.root)).filter(name=>name.endsWith('.tmp')),[]);});
test('concurrent authentication activity, CSRF generation, and revocation persist valid snapshots',async()=>{const {service,store,user,req}=await fixture();const sessions=await Promise.all(Array.from({length:12},()=>service.createSession(user,req)));await Promise.all(sessions.map(async({token,record},index)=>{const request={...req,headers:{...req.headers,cookie:`${COOKIE_NAME}=${token}`}};const auth=await service.authenticate(request);assert.ok(auth);request.auth=auth;await service.csrf(request);if(index%2===0)await service.revoke(record);}));const saved=JSON.parse(await readFile(store.sessionPath,'utf8'));assert.equal(saved.length,12);assert.equal(saved.filter(s=>s.csrfTokenHash).length,12);assert.equal(saved.filter(s=>s.revokedAt).length,6);assert.deepEqual((await readdir(store.root)).filter(name=>name.endsWith('.tmp')),[]);});
test('users and sessions use independent ordered write queues with stable snapshots',async()=>{const {store}=await fixture();const writes=[];for(let i=0;i<20;i++){store.users.push({id:`u${i}`});writes.push(store.saveUsers());store.sessions.push({id:`s${i}`});writes.push(store.saveSessions());}await Promise.all(writes);assert.equal(JSON.parse(await readFile(store.userPath,'utf8')).length,21);assert.equal(JSON.parse(await readFile(store.sessionPath,'utf8')).length,20);assert.deepEqual((await readdir(store.root)).filter(name=>name.endsWith('.tmp')),[]);});

test('production bootstrap fails without the exact explicit flag',async()=>{const f=await bootstrapFixture({NODE_ENV:'production',ALLOW_PRODUCTION_BOOTSTRAP:'TRUE',BOOTSTRAP_ADMIN_EMAIL:'owner@example.com',BOOTSTRAP_ADMIN_PASSWORD:'Correct-Horse-7-Battery!'});try{await assert.rejects(f.init(),/explicitly enabled secure bootstrap/);assert.equal(f.store.users.length,0);}finally{await rm(f.root,{recursive:true,force:true});}});
test('production bootstrap fails with incomplete credentials',async()=>{for(const values of [{BOOTSTRAP_ADMIN_EMAIL:'owner@example.com'},{BOOTSTRAP_ADMIN_PASSWORD:'Correct-Horse-7-Battery!'}]){const f=await bootstrapFixture({NODE_ENV:'production',ALLOW_PRODUCTION_BOOTSTRAP:'true',...values});try{await assert.rejects(f.init(),/credentials/);assert.equal(f.store.users.length,0);}finally{await rm(f.root,{recursive:true,force:true});}}});
test('production bootstrap rejects invalid email and weak passwords',async()=>{for(const [email,password] of [['not-an-email','Correct-Horse-7-Battery!'],['owner@example.com','password123456789'],['owner@example.com','too-short']]){const f=await bootstrapFixture({NODE_ENV:'production',ALLOW_PRODUCTION_BOOTSTRAP:'true',BOOTSTRAP_ADMIN_EMAIL:email,BOOTSTRAP_ADMIN_PASSWORD:password});try{await assert.rejects(f.init(),/security requirements/);assert.equal(f.store.users.length,0);}finally{await rm(f.root,{recursive:true,force:true});}}});
test('valid production bootstrap creates one active Admin with a non-plaintext Argon2id password',async()=>{const password='Correct-Horse-7-Battery!',f=await bootstrapFixture({NODE_ENV:'production',ALLOW_PRODUCTION_BOOTSTRAP:'true',BOOTSTRAP_ADMIN_EMAIL:'Owner@Example.com',BOOTSTRAP_ADMIN_PASSWORD:password});try{await f.init();assert.equal(f.store.users.length,1);const user=f.store.users[0];assert.equal(user.email,'owner@example.com');assert.deepEqual(user.roles,['Admin']);assert.equal(user.active,true);assert.equal(user.mustChangePassword,false);assert.notEqual(user.passwordHash,password);assert.match(user.passwordHash,/^\$argon2id\$/);const disk=await readFile(f.store.userPath,'utf8');assert.ok(!disk.includes(password));}finally{await rm(f.root,{recursive:true,force:true});}});
test('restart does not create a duplicate and ignores every bootstrap variable for an existing Admin',async()=>{const password='Correct-Horse-7-Battery!',f=await bootstrapFixture({NODE_ENV:'production',ALLOW_PRODUCTION_BOOTSTRAP:'true',BOOTSTRAP_ADMIN_EMAIL:'owner@example.com',BOOTSTRAP_ADMIN_PASSWORD:password});try{await f.init();const restarted=new SecurityService({store:new FileSecurityStore(f.root),appOrigin:'https://erp.example.invalid'});await withBootstrapEnv({NODE_ENV:'production',ALLOW_PRODUCTION_BOOTSTRAP:'false',BOOTSTRAP_ADMIN_EMAIL:'invalid',BOOTSTRAP_ADMIN_PASSWORD:'weak'},()=>restarted.init());assert.equal(restarted.store.users.length,1);}finally{await rm(f.root,{recursive:true,force:true});}});
test('bootstrap secret is absent from errors, console output, and audit data',async()=>{const password='Correct-Horse-7-Battery!',f=await bootstrapFixture({NODE_ENV:'production',ALLOW_PRODUCTION_BOOTSTRAP:'true',BOOTSTRAP_ADMIN_EMAIL:'owner@example.com',BOOTSTRAP_ADMIN_PASSWORD:password}),messages=[];const originalLog=console.log,originalError=console.error;console.log=(...args)=>messages.push(args.join(' '));console.error=(...args)=>messages.push(args.join(' '));try{await f.init();assert.ok(!messages.join('\n').includes(password));const audit=await readFile(f.store.auditPath,'utf8').catch(()=> '');assert.ok(!audit.includes(password));}finally{console.log=originalLog;console.error=originalError;await rm(f.root,{recursive:true,force:true});}});
test('bootstrapped administrator credentials authenticate and issue a persisted real session',async()=>{const password='Correct-Horse-7-Battery!',f=await bootstrapFixture({NODE_ENV:'production',ALLOW_PRODUCTION_BOOTSTRAP:'true',BOOTSTRAP_ADMIN_EMAIL:'owner@example.com',BOOTSTRAP_ADMIN_PASSWORD:password});try{await f.init();const {verify}=await import('argon2');const user=f.store.users.find(u=>u.active&&u.email==='owner@example.com');assert.equal(await verify(user.passwordHash,password),true);const request={headers:{'user-agent':'bootstrap-login-test'},socket:{remoteAddress:'127.0.0.1'}};const {token}=await f.service.createSession(user,request);request.headers.cookie=`${COOKIE_NAME}=${token}`;const auth=await f.service.authenticate(request);assert.equal(auth.user.id,user.id);assert.equal(JSON.parse(await readFile(f.store.sessionPath,'utf8')).length,1);}finally{await rm(f.root,{recursive:true,force:true});}});
