const field=(value=null,confidence=null,sourceLabel=null,providerFieldName=null,boundingRegions=[],sourceText=null)=>({value,normalizedValue:value,confidence,pageNumber:boundingRegions?.[0]?.pageNumber||null,boundingPolygon:boundingRegions?.[0]?.polygon||null,sourceText:sourceText??(value==null?null:String(value)),sourceLabel,providerFieldName,source:'provider'});
const content=(f)=>f?.content ?? f?.valueString ?? f?.valueDate ?? f?.valueCurrency?.amount ?? f?.valueNumber ?? null;
const amount=(f)=>Number(f?.valueCurrency?.amount ?? f?.valueNumber ?? content(f) ?? 0)||0;
const months={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};
const iso=(y,m,d)=>{ const dt=new Date(Date.UTC(Number(y),Number(m)-1,Number(d))); return dt.getUTCFullYear()===Number(y)&&dt.getUTCMonth()===Number(m)-1&&dt.getUTCDate()===Number(d)?dt:null; };
export function parseInvoiceDate(input){ const s=String(input||'').trim(); if(!s)return null; let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/); if(m)return iso(m[1],m[2],m[3]); m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2}|\d{4})$/); if(m){ const y=Number(m[3].length===2?`20${m[3]}`:m[3]); return iso(y,m[1],m[2]); } m=s.match(/^(\d{1,2})[-\s]([A-Za-z]{3,9})[-\s,]+(\d{4})$/); if(m&&months[m[2].toLowerCase()])return iso(m[3],months[m[2].toLowerCase()],m[1]); m=s.match(/^([A-Za-z]{3,9})\s+(\d{1,2}),?\s+(\d{4})$/); if(m&&months[m[1].toLowerCase()])return iso(m[3],months[m[1].toLowerCase()],m[2]); return null; }
export function extractAzureDate(field){ const candidate=field?.valueDate ?? field?.valueString ?? field?.content ?? null; const parsed=parseInvoiceDate(candidate); return parsed?parsed.toISOString().slice(0,10):null; }
const pickField=(fields,...names)=>names.map(n=>fields?.[n]).find(Boolean);
export function normalizeAzureInvoiceResult(providerResult){
  const doc=providerResult?.analyzeResult?.documents?.[0]||{}; const f=doc.fields||{}; const raw=providerResult?.analyzeResult?.content||''; const labelVal=(label)=>{const m=raw.match(new RegExp(label+'[ \t]*[:#-]?[ \t]*([^\\n\\r]*)','i')); return (m?.[1]||'').trim();};
  const invoiceDateField=pickField(f,'InvoiceDate','invoiceDate'); const dueDateField=pickField(f,'DueDate','dueDate');
  const lines=(f.Items?.valueArray||[]).map((it,i)=>{const p=it.valueObject||{}; return {lineNumber:i+1,vendorItemNumber:content(p.ProductCode)||'',inventoryId:content(p.ProductCode)||'',description:content(p.Description)||'',quantity:amount(p.Quantity)||0,uom:content(p.Unit)||'',unitCost:amount(p.UnitPrice)||0,extendedCost:amount(p.Amount)||0,discount:0,tax:0,lineAmount:amount(p.Amount)||0,confidence:it.confidence||null,source:'provider',pageNumber:it.boundingRegions?.[0]?.pageNumber||null,boundingPolygon:it.boundingRegions?.[0]?.polygon||null};});
  const subtotal=amount(f.SubTotal), freight=amount(f.Shipping), tax=amount(f.TotalTax), discount=amount(f.TotalDiscount), gross=amount(f.InvoiceTotal), due=amount(f.AmountDue);
  return {documentType:field('Vendor Invoice',doc.confidence,'Document Type','DocumentType'),vendorName:field(content(f.VendorName),f.VendorName?.confidence,'Vendor Name','VendorName',f.VendorName?.boundingRegions),vendorAddress:field(content(f.VendorAddress),f.VendorAddress?.confidence,'Vendor Address','VendorAddress',f.VendorAddress?.boundingRegions),vendorPhone:field(content(f.VendorPhoneNumber),f.VendorPhoneNumber?.confidence,'Vendor Phone','VendorPhoneNumber',f.VendorPhoneNumber?.boundingRegions),invoiceNumber:field(content(f.InvoiceId),f.InvoiceId?.confidence,'Invoice Number','InvoiceId',f.InvoiceId?.boundingRegions),invoiceDate:field(extractAzureDate(invoiceDateField),invoiceDateField?.confidence,'Invoice Date','InvoiceDate',invoiceDateField?.boundingRegions,content(invoiceDateField)),dueDate:field(extractAzureDate(dueDateField),dueDateField?.confidence,'Due Date','DueDate',dueDateField?.boundingRegions,content(dueDateField)),customerPurchaseOrderNumber:field(content(f.PurchaseOrder),f.PurchaseOrder?.confidence,'Customer PO Number','PurchaseOrder',f.PurchaseOrder?.boundingRegions),vendorOrderNumber:field(labelVal('OUR\\s+ORDER\\s+NUMBER')||null,.9,'OUR ORDER NUMBER','VendorOrderNumber'),currency:field(f.InvoiceTotal?.valueCurrency?.currencyCode||'USD',f.InvoiceTotal?.confidence,'Currency','Currency',f.InvoiceTotal?.boundingRegions),paymentTerms:field(content(f.PaymentTerm),f.PaymentTerm?.confidence,'Terms','PaymentTerm',f.PaymentTerm?.boundingRegions),merchandiseSubtotal:field(subtotal,f.SubTotal?.confidence,'Subtotal','SubTotal',f.SubTotal?.boundingRegions),freightAmount:field(freight,f.Shipping?.confidence,'Freight','Shipping',f.Shipping?.boundingRegions),miscellaneousCharges:field(0,null,'Miscellaneous Charges','MiscellaneousCharges'),discountAmount:field(discount,f.TotalDiscount?.confidence,'Discount','TotalDiscount',f.TotalDiscount?.boundingRegions),taxAmount:field(tax,f.TotalTax?.confidence,'Tax','TotalTax',f.TotalTax?.boundingRegions),grossInvoiceAmount:field(gross,f.InvoiceTotal?.confidence,'Invoice Total','InvoiceTotal',f.InvoiceTotal?.boundingRegions),amountPaidOrDepositApplied:field(Number((raw.match(/Less\s+Deposit\s+Paid[^0-9]*([0-9,]+\.[0-9]{2})/i)||[])[1]?.replace(/,/g,'')||0),.9,'Less Deposit Paid','AmountPaid'),amountDue:field(due,f.AmountDue?.confidence,'Amount Due','AmountDue',f.AmountDue?.boundingRegions),lines,pages:providerResult?.analyzeResult?.pages||[],rawText:raw,providerName:providerResult.providerName,providerModel:providerResult.providerModel,providerRequestId:providerResult.providerRequestId};
}
export function flattenRecognizedInvoice(n){ const v=(x)=>x?.normalizedValue ?? x?.value ?? ''; return {documentType:v(n.documentType),vendorName:v(n.vendorName),vendorAddress:v(n.vendorAddress),vendorPhone:v(n.vendorPhone),invoiceNumber:v(n.invoiceNumber),invoiceDate:v(n.invoiceDate),invoiceDateSourceText:n.invoiceDate?.sourceText,dueDate:v(n.dueDate),dueDateSourceText:n.dueDate?.sourceText,dueDateSource:v(n.dueDate)?'Azure':'',purchaseOrderNumber:v(n.customerPurchaseOrderNumber),poNumber:v(n.customerPurchaseOrderNumber),vendorOrderNumber:v(n.vendorOrderNumber),currency:v(n.currency)||'USD',recognizedTermsText:v(n.paymentTerms),terms:v(n.paymentTerms),paymentTerms:v(n.paymentTerms),paymentTermsSource:v(n.paymentTerms)?'Azure':'',subtotal:Number(v(n.merchandiseSubtotal)||0),merchandiseSubtotal:Number(v(n.merchandiseSubtotal)||0),freightAmount:Number(v(n.freightAmount)||0),miscellaneousCharges:Number(v(n.miscellaneousCharges)||0),discount:Number(v(n.discountAmount)||0),taxAmount:Number(v(n.taxAmount)||0),azureInvoiceTotal:Number(v(n.grossInvoiceAmount)||0),grossInvoiceAmount:Number(v(n.grossInvoiceAmount)||0),prepaymentApplied:Number(v(n.amountPaidOrDepositApplied)||0),amountDue:Number(v(n.amountDue)||0),balanceDue:Number(v(n.amountDue)||0),totalAmount:Number(v(n.grossInvoiceAmount)||0),rawText:n.rawText,providerName:n.providerName,providerDocumentId:n.providerRequestId,lines:(n.lines||[]).map(l=>({lineNumber:l.lineNumber,itemCode:l.inventoryId,vendorItemCode:l.vendorItemNumber,description:l.description,qty:l.quantity,uom:l.uom,unitPrice:l.unitCost,extendedAmount:l.extendedCost,discount:l.discount,tax:l.tax,glAccountSuggestion:'5110',confidence:l.confidence}))}; }
