export const AP_INVOICE_CLASSIFICATIONS = [
  'PO Goods Invoice — Three-Way Match','PO Service Invoice — Two-Way Match','Non-PO Expense Invoice','Recurring Utility Invoice','Recurring Subscription or Contract Invoice','Freight or Logistics Invoice','Tax or Government Fee','Fixed Asset or Capital Expenditure','Prepayment or Vendor Deposit','Credit or Debit Adjustment','Intercompany Invoice','Other — Manual Review Required'
];
const round = value => Math.round((Number(value || 0) + Number.EPSILON) * 100) / 100;
export function calculateApBillTotals(lines = [], { taxTotal = 0, freight = 0 } = {}) {
  const calculatedLines = lines.map(line => { const quantity=Number(line.qty ?? line.quantity ?? 0),unitCost=Number(line.unitCost ?? 0),discountAmount=round(line.discountAmount);if(!Number.isFinite(quantity)||!Number.isFinite(unitCost)||quantity<0||unitCost<0||discountAmount<0)throw new Error('AP Bill quantity, unit cost, and discount must be non-negative numbers.');const extendedCost=round(quantity*unitCost),amount=round(extendedCost-discountAmount);return {...line,qty:quantity,unitCost,discountAmount,extendedCost,amount}; });
  const subtotal=round(calculatedLines.reduce((sum,line)=>sum+line.extendedCost,0));
  const discountTotal=round(calculatedLines.reduce((sum,line)=>sum+line.discountAmount,0));
  const netLines=round(calculatedLines.reduce((sum,line)=>sum+line.amount,0));
  return {lines:calculatedLines,subtotal,discountTotal,netLines,taxTotal:round(taxTotal),freight:round(freight),invoiceTotal:round(netLines+Number(taxTotal||0)+Number(freight||0))};
}
export const DEFAULT_AP_DECISION_RULES = [
 {ruleId:'AP-3WAY-001',name:'Three-Way Match Auto Approval',classification:AP_INVOICE_CLASSIFICATIONS[0],priceTolerancePercent:2,priceToleranceAmount:100,totalTolerancePercent:2,totalToleranceAmount:100,quantityTolerance:0,action:'Auto Approved',priority:100,active:true,effectiveFrom:'2026-01-01',effectiveTo:null,createdBy:'system',approvedBy:'controller',version:1},
 {ruleId:'AP-2WAY-001',name:'Service PO Two-Way Review',classification:AP_INVOICE_CLASSIFICATIONS[1],totalTolerancePercent:2,totalToleranceAmount:100,action:'Auto Approved',priority:90,active:true,effectiveFrom:'2026-01-01',effectiveTo:null,createdBy:'system',approvedBy:'controller',version:1},
 {ruleId:'AP-NONPO-001',name:'Non-PO Approval Control',classification:AP_INVOICE_CLASSIFICATIONS[2],action:'Approval Required',priority:10,active:true,effectiveFrom:'2026-01-01',effectiveTo:null,createdBy:'system',approvedBy:'controller',version:1}
];
const normalizedInvoice = value => String(value||'').toLowerCase().replace(/[^a-z0-9]/g,'');
export function evaluateApInvoice({vendor={},invoice={},lines=[],purchaseOrder=null,receipts=[],recurringProfile=null,rules=DEFAULT_AP_DECISION_RULES,duplicateResults=[]}={}) {
 const poNumber=invoice.poNumber||lines.find(line=>line.poNumber)?.poNumber||'',hasPo=!!(purchaseOrder||poNumber),isService=!!(purchaseOrder?.receiptNotRequired||purchaseOrder?.serviceConfirmationRequired||purchaseOrder?.poType==='SV');
 let classification=invoice.invoiceClassification||invoice.suggestedClassification||(hasPo?(isService?AP_INVOICE_CLASSIFICATIONS[1]:AP_INVOICE_CLASSIFICATIONS[0]):AP_INVOICE_CLASSIFICATIONS[2]);
 const totals=calculateApBillTotals(lines,{taxTotal:invoice.taxTotal,freight:invoice.freight}),poTotal=round(purchaseOrder?.openAmount??purchaseOrder?.total??0),variance=round(totals.invoiceTotal-poTotal),variancePercent=poTotal?round(Math.abs(variance)/poTotal*100):0;
 const priceVariance=round(invoice.priceVariance??variance),priceVariancePercent=poTotal?round(Math.abs(priceVariance)/poTotal*100):0,quantityVariance=round(invoice.quantityVariance||0);
 const today=invoice.date||new Date().toISOString().slice(0,10),applicable=rules.filter(rule=>rule.active&&rule.classification===classification&&(!rule.effectiveFrom||today>=rule.effectiveFrom)&&(!rule.effectiveTo||today<=rule.effectiveTo)&&(!rule.vendorId||rule.vendorId===vendor.id)&&(!rule.branch||rule.branch===invoice.branch)).sort((a,b)=>Number(!!b.vendorId)+Number(!!b.branch)-Number(!!a.vendorId)-Number(!!a.branch)||b.priority-a.priority)[0];
 const duplicate=duplicateResults.length>0||invoice.duplicate===true,reasons=[],exceptions=[];let approvalRequirement='Approval Required';
 const vendorMatches=!purchaseOrder||purchaseOrder.vendorId===vendor.id,currencyMatches=!purchaseOrder||!purchaseOrder.currency||purchaseOrder.currency===(invoice.currency||'USD'),receiptExists=isService?(purchaseOrder?.receiptNotRequired||receipts.length>0):receipts.length>0;
 if(duplicate){approvalRequirement='Exception Review';exceptions.push('Probable duplicate invoice');reasons.push('Duplicate controls block automatic approval.');}
 else if(classification===AP_INVOICE_CLASSIFICATIONS[0]){const hardFailures=[];if(!vendorMatches)hardFailures.push('Vendor does not match PO');if(!currencyMatches)hardFailures.push('Currency does not match PO');if(!purchaseOrder||!['Open','Partially Received','Received'].includes(purchaseOrder.status))hardFailures.push('PO is not valid and open');if(!receiptExists)hardFailures.push('No qualifying receipt exists');if(!invoice.invoiceNumber)hardFailures.push('Invoice number is required');if(quantityVariance>Number(applicable?.quantityTolerance??0))hardFailures.push('Quantity exceeds received availability');if(priceVariancePercent>Number(applicable?.priceTolerancePercent??0))hardFailures.push(`Price variance ${priceVariancePercent.toFixed(2)}% exceeds limit`);if(Math.abs(priceVariance)>Number(applicable?.priceToleranceAmount??0))hardFailures.push(`Price variance ${Math.abs(priceVariance).toFixed(2)} exceeds dollar limit`);if(variancePercent>Number(applicable?.totalTolerancePercent??0))hardFailures.push(`Total variance ${variancePercent.toFixed(2)}% exceeds limit`);if(Math.abs(variance)>Number(applicable?.totalToleranceAmount??0))hardFailures.push(`Total variance ${Math.abs(variance).toFixed(2)} exceeds dollar limit`);approvalRequirement=hardFailures.length?'Exception Review':(applicable?.action||'Approval Required');reasons.push(...(hardFailures.length?hardFailures:[`Vendor, PO, receipt, quantity, price, and amount controls passed rule ${applicable?.ruleId}.`]));exceptions.push(...hardFailures);}
 else if(classification===AP_INVOICE_CLASSIFICATIONS[1]){const failures=[];if(!vendorMatches)failures.push('Vendor does not match service PO');if(!purchaseOrder)failures.push('Service PO is required');if(purchaseOrder?.serviceConfirmationRequired&&!receipts.length)failures.push('Service confirmation is required');if(Math.abs(variance)>Number(applicable?.totalToleranceAmount??0)||variancePercent>Number(applicable?.totalTolerancePercent??0))failures.push('Service PO amount tolerance failed');approvalRequirement=failures.length?'Exception Review':(applicable?.action||'Approval Required');reasons.push(...(failures.length?failures:['Service PO two-way controls passed.']));exceptions.push(...failures);}
 else if(['Recurring Utility Invoice','Recurring Subscription or Contract Invoice'].includes(classification)){const profilePass=recurringProfile?.active&&recurringProfile.classification===classification&&(!recurringProfile.maximumInvoiceAmount||totals.invoiceTotal<=recurringProfile.maximumInvoiceAmount)&&(recurringProfile.approvedBranches||[]).includes(invoice.branch)&&lines.every(line=>(recurringProfile.approvedAccounts||[]).includes(line.expenseAccount));approvalRequirement=profilePass?'Auto Approved':'Exception Review';reasons.push(profilePass?`Approved recurring profile ${recurringProfile.ruleId||recurringProfile.id} passed.`:'Recurring classification retained, but no active approved profile passed all controls.');if(!profilePass)exceptions.push(reasons.at(-1));}
 else {approvalRequirement=applicable?.action||'Approval Required';reasons.push(applicable?`Rule ${applicable.ruleId} requires ${approvalRequirement}.`:'Non-PO invoices require approval by default.');}
 const components={vendorMatch:vendorMatches?100:0,poMatch:hasPo?100:0,receiptMatch:receiptExists?100:0,quantityMatch:Math.max(0,100-Math.abs(quantityVariance)),priceMatch:Math.max(0,round(100-priceVariancePercent)),totalMatch:Math.max(0,round(100-variancePercent))};
 return {classification,classificationConfidence:Number(invoice.classificationConfidence??(classification===invoice.invoiceClassification?100:85)),matchType:classification.includes('Three-Way')?'Three-Way':classification.includes('Two-Way')?'Two-Way':'Non-PO',matchScore:round(Object.values(components).reduce((a,b)=>a+b,0)/6),matchComponents:components,variances:{priceAmount:priceVariance,pricePercent:priceVariancePercent,totalAmount:variance,totalPercent:variancePercent,quantity:quantityVariance},approvalRequirement,approvalRuleId:applicable?.ruleId||recurringProfile?.ruleId||'',reasons,exceptions,totals,approvalDecisionSource:applicable?'System Rule':recurringProfile?'Recurring Profile':'Company Default'};
}
export function learnedClassificationSuggestion(corrections=[],vendorId){const relevant=corrections.filter(c=>c.vendorId===vendorId);if(relevant.length<5)return null;const counts=relevant.reduce((m,c)=>(m[c.selectedClassification]=(m[c.selectedClassification]||0)+1,m),{}),[classification,count]=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]||[];const consistency=count/relevant.length;if(consistency<.9)return null;return{classification,confidence:Math.round(consistency*100),sampleSize:relevant.length,reason:`Suggested ${classification} because ${count} of ${relevant.length} prior reviewed corrections matched.`,canAutoApprove:false,proposedRuleStatus:'Pending Administrator Approval'};}
