const round=value=>Number(Number(value||0).toFixed(2));
const monthRange=(from,to)=>{const result=[];let cursor=new Date(`${from}-01T00:00:00Z`),end=new Date(`${to}-01T00:00:00Z`);while(cursor<=end&&result.length<240){result.push(cursor.toISOString().slice(0,7));cursor.setUTCMonth(cursor.getUTCMonth()+1);}return result;};
const previousMonth=period=>{const date=new Date(`${period}-01T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()-1);return date.toISOString().slice(0,7);};

export function createFinancialReportingService({accounts,postedLines,companyName='ERP Company'}){
 const classification=account=>({statement:account.financialStatement||(account.accountType==='Income/Expense'?'ProfitLoss':'BalanceSheet'),group:account.reportGroup||(account.accountType==='Income/Expense'?'Unclassified Income / Expense':'Unclassified Balance Sheet'),subgroup:account.reportSubgroup||'',cashFlowClass:account.cashFlowClass||'None',cashEquivalent:account.cashEquivalent===true,retainedEarnings:account.retainedEarnings===true,distribution:account.distribution===true});
 const raw=(from='',to='')=>accounts.map(account=>{const all=postedLines(account.code),baseline=round(Number(account.balance||0)-all.reduce((s,l)=>s+Number(l.debit||0)-Number(l.credit||0),0)),selected=all.filter(l=>(!from||l.postPeriod>=from)&&(!to||l.postPeriod<=to)),through=all.filter(l=>!to||l.postPeriod<=to),c=classification(account);return{accountCode:account.code,accountName:account.name,accountType:account.accountType,...c,debit:round(selected.reduce((s,l)=>s+l.debit,0)),credit:round(selected.reduce((s,l)=>s+l.credit,0)),activity:round(selected.reduce((s,l)=>s+l.debit-l.credit,0)),balance:round(baseline+through.reduce((s,l)=>s+l.debit-l.credit,0))};});
 const groupRows=(rows,value='amount')=>[...rows.reduce((map,row)=>map.set(row.group,[...(map.get(row.group)||[]),row]),new Map()).entries()].map(([name,details])=>({name,details,total:round(details.reduce((s,r)=>s+r[value],0))}));
 const trialBalance=({fromPeriod='',toPeriod='',includeZero=true}={})=>{let rows=raw(fromPeriod,toPeriod).map(r=>({...r,accountNumber:r.accountCode,accountTitle:r.accountName}));if(!includeZero)rows=rows.filter(r=>r.debit||r.credit||r.balance);return{companyName,reportName:'Trial Balance',fromPeriod,toPeriod,rows,totals:{totalDebits:round(rows.reduce((s,r)=>s+r.debit,0)),totalCredits:round(rows.reduce((s,r)=>s+r.credit,0)),netDifference:round(rows.reduce((s,r)=>s+r.debit-r.credit,0))}};};
 const balanceSheet=({asOf='',includeZero=false}={})=>{let rows=raw('',asOf).filter(r=>r.statement==='BalanceSheet').map(r=>({...r,amount:r.balance}));if(!includeZero)rows=rows.filter(r=>r.amount);const assets=rows.filter(r=>r.amount>=0),liabilitiesEquity=rows.filter(r=>r.amount<0).map(r=>({...r,amount:-r.amount})),totalAssets=round(assets.reduce((s,r)=>s+r.amount,0)),totalLiabilitiesEquity=round(liabilitiesEquity.reduce((s,r)=>s+r.amount,0));return{companyName,reportName:'Balance Sheet',asOf,sections:[{name:'ASSETS',groups:groupRows(assets)},{name:'LIABILITIES & EQUITY',groups:groupRows(liabilitiesEquity)}],totalAssets,totalLiabilitiesEquity,difference:round(totalAssets-totalLiabilitiesEquity),balanced:Math.abs(totalAssets-totalLiabilitiesEquity)<.01};};
 const profitLoss=({fromPeriod='',toPeriod='',includeZero=false,view='total'}={})=>{const months=view==='monthly'?monthRange(fromPeriod,toPeriod):[];let rows=raw(fromPeriod,toPeriod).filter(r=>r.statement==='ProfitLoss').map(r=>({...r,amount:round(r.credit-r.debit),months:Object.fromEntries(months.map(m=>{const x=raw(m,m).find(a=>a.accountCode===r.accountCode);return[m,round(x.credit-x.debit)];}))}));if(!includeZero)rows=rows.filter(r=>r.amount||Object.values(r.months).some(Boolean));const revenue=rows.filter(r=>r.amount>=0),expenses=rows.filter(r=>r.amount<0).map(r=>({...r,amount:-r.amount,months:Object.fromEntries(Object.entries(r.months).map(([m,v])=>[m,-v]))})),totalRevenue=round(revenue.reduce((s,r)=>s+r.amount,0)),totalExpenses=round(expenses.reduce((s,r)=>s+r.amount,0));return{companyName,reportName:'Profit & Loss',fromPeriod,toPeriod,view,months,sections:[{name:'REVENUE',groups:groupRows(revenue)},{name:'EXPENSES',groups:groupRows(expenses)}],rows:[...revenue,...expenses],totalRevenue,totalExpenses,netIncome:round(totalRevenue-totalExpenses)};};
 const cashFlow=({fromPeriod='',toPeriod='',includeZero=false}={})=>{const pl=profitLoss({fromPeriod,toPeriod,includeZero:true}),rows=raw(fromPeriod,toPeriod).filter(r=>r.cashFlowClass!=='None').map(r=>({...r,amount:round(-r.activity)}));const sections=['Operating','Investing','Financing'].map(name=>({name:`CASH FLOWS FROM ${name.toUpperCase()} ACTIVITIES`,groups:groupRows(rows.filter(r=>r.cashFlowClass===name))})),beginningCash=round(raw('',fromPeriod?previousMonth(fromPeriod):'').filter(r=>r.cashEquivalent).reduce((s,r)=>s+r.balance,0)),endingCash=round(raw('',toPeriod).filter(r=>r.cashEquivalent).reduce((s,r)=>s+r.balance,0)),netChange=round(endingCash-beginningCash);return{companyName,reportName:'Cash Flow Statement',method:'Indirect',fromPeriod,toPeriod,netIncome:pl.netIncome,sections,beginningCash,netChange,endingCash,difference:round(beginningCash+netChange-endingCash),reconciled:Math.abs(beginningCash+netChange-endingCash)<.01};};
 const retainedEarnings=({fromPeriod='',toPeriod=''}={})=>{const beginning=round(raw('',fromPeriod).filter(r=>r.retainedEarnings).reduce((s,r)=>s-r.balance,0)),netIncome=profitLoss({fromPeriod,toPeriod,includeZero:true}).netIncome,distributions=round(raw(fromPeriod,toPeriod).filter(r=>r.distribution).reduce((s,r)=>s+r.debit-r.credit,0)),ending=round(beginning+netIncome-distributions);return{companyName,reportName:'Statement of Retained Earnings',fromPeriod,toPeriod,beginningRetainedEarnings:beginning,netIncome,adjustments:0,distributions,endingRetainedEarnings:ending,reconciled:true,difference:0};};
 return{getPostedAccountActivity:raw,getTrialBalance:trialBalance,getBalanceSheet:balanceSheet,getProfitAndLoss:profitLoss,getCashFlow:cashFlow,getRetainedEarningsStatement:retainedEarnings};
}
