import {
  financialReportMappingForAccount,
  financialStatementForAccount
} from './accountStatementClassification.js';

const round=value=>Number(Number(value||0).toFixed(2));
const monthRange=(from,to)=>{const result=[];let cursor=new Date(`${from}-01T00:00:00Z`),end=new Date(`${to}-01T00:00:00Z`);while(cursor<=end&&result.length<240){result.push(cursor.toISOString().slice(0,7));cursor.setUTCMonth(cursor.getUTCMonth()+1);}return result;};
const previousMonth=period=>{const date=new Date(`${period}-01T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()-1);return date.toISOString().slice(0,7);};
const configuredCashFlowClass=value=>['Operating','Investing','Financing'].includes(value)?value:'';
const accountText=account=>`${account?.code||''} ${account?.name||''}`.toLowerCase();
const inferredCashEquivalent=account=>{const text=accountText(account);return /(cash|checking|operating account|petty cash|money market)/i.test(text)&&!/(restricted|escrow|letter of credit|deposit on|customer deposit|vendor deposit)/i.test(text);};
const inferredCashFlowClass=(account,statement,cashEquivalent)=>{
 if(statement!=='BalanceSheet'||cashEquivalent)return'None';
 const code=String(account?.code||'').trim(),text=accountText(account);
 if(/(debt|loan|lending|line of credit|revolver|revolving|lease liability|note payable|note pyble|deferred financing|common stock|paid in capital|dividend|equity|capital contribution|capital distribution)/i.test(text)||/^30\d\d$/.test(code))return'Financing';
 if(/^(17|18)\d\d$/.test(code)||/(fixed asset|property|plant|equipment|machinery|automobile|truck|construction in progress|leasehold improvement|developed technology|trade name|patent|trademark|goodwill|right of use asset|investment in)/i.test(text))return'Investing';
 return'Operating';
};
const mappedFs5=(account,statement)=>{
 const mapped=financialReportMappingForAccount(account?.code);
 if(mapped)return mapped.fs5;
 if(['Asset','Liability','Equity','Revenue','Expense'].includes(account?.accountType))return account.accountType;
 if(statement==='ProfitLoss'&&account?.accountType==='Income/Expense')return'';
 if(statement==='BalanceSheet'&&account?.accountType==='Asset/Liability')return'';
 return'';
};
const balanceSheetClass=row=>['Asset','Liability','Equity'].includes(row.fs5)?row.fs5:['Asset','Liability','Equity'].includes(row.accountType)?row.accountType:(row.balance>=0?'Asset':'Liability');
const profitLossClass=row=>['Revenue','Expense'].includes(row.fs5)?row.fs5:['Revenue','Expense'].includes(row.accountType)?row.accountType:(row.credit-row.debit>=0?'Revenue':'Expense');

export function createFinancialReportingService({accounts,postedLines,companyName='ERP Company'}){
 const classification=account=>{const mapped=financialReportMappingForAccount(account.code),statement=mapped?.statement||financialStatementForAccount(account.code,account.financialStatement),fs5=mapped?.fs5||mappedFs5(account,statement),explicitClass=configuredCashFlowClass(account.cashFlowClass),cashEquivalent=account.cashEquivalent===true||(!explicitClass&&inferredCashEquivalent(account)),cashFlowClass=cashEquivalent?'None':(explicitClass||(account.cashFlowClass==='None'||!account.cashFlowClass?inferredCashFlowClass(account,statement,cashEquivalent):'None')),group=mapped?.reportGroup||account.reportGroup||(statement==='ProfitLoss'?'Unclassified Income / Expense':cashFlowClass==='Operating'?'Operating Working Capital':cashFlowClass==='Investing'?'Investing Activities':cashFlowClass==='Financing'?'Financing Activities':'Unclassified Balance Sheet'),subgroup=mapped?.reportSubgroup||account.reportSubgroup||'';return{statement,fs5,group,subgroup,cashFlowClass,cashEquivalent,retainedEarnings:account.retainedEarnings===true||account.code==='3090',distribution:account.distribution===true};};
 const raw=(from='',to='')=>accounts.map(account=>{const all=postedLines(account.code),baseline=round(Number(account.balance||0)-all.reduce((s,l)=>s+Number(l.debit||0)-Number(l.credit||0),0)),selected=all.filter(l=>(!from||l.postPeriod>=from)&&(!to||l.postPeriod<=to)),through=all.filter(l=>!to||l.postPeriod<=to),c=classification(account);return{accountCode:account.code,accountName:account.name,accountType:account.accountType,...c,debit:round(selected.reduce((s,l)=>s+Number(l.debit||0),0)),credit:round(selected.reduce((s,l)=>s+Number(l.credit||0),0)),activity:round(selected.reduce((s,l)=>s+Number(l.debit||0)-Number(l.credit||0),0)),balance:round(baseline+through.reduce((s,l)=>s+Number(l.debit||0)-Number(l.credit||0),0))};});
 const groupRows=(rows,value='amount')=>[...rows.reduce((map,row)=>map.set(row.group,[...(map.get(row.group)||[]),row]),new Map()).entries()].map(([name,sourceDetails])=>{const hasSubgroups=sourceDetails.some(row=>String(row.subgroup||'').trim()),subgroups=hasSubgroups?[...sourceDetails.reduce((map,row)=>{const subgroup=String(row.subgroup||'Other').trim()||'Other';map.set(subgroup,[...(map.get(subgroup)||[]),row]);return map;},new Map()).entries()].map(([subgroupName,details])=>({name:subgroupName,details,total:round(details.reduce((s,r)=>s+r[value],0))})):[],details=subgroups.length?subgroups.flatMap(subgroup=>subgroup.details):sourceDetails;return{name,details,total:round(details.reduce((s,r)=>s+r[value],0)),...(subgroups.length?{subgroups}:{})};});
 const trialBalance=({fromPeriod='',toPeriod='',includeZero=true}={})=>{let rows=raw(fromPeriod,toPeriod).map(r=>({...r,accountNumber:r.accountCode,accountTitle:r.accountName}));if(!includeZero)rows=rows.filter(r=>r.debit||r.credit||r.balance);return{companyName,reportName:'Trial Balance',fromPeriod,toPeriod,rows,totals:{totalDebits:round(rows.reduce((s,r)=>s+r.debit,0)),totalCredits:round(rows.reduce((s,r)=>s+r.credit,0)),netDifference:round(rows.reduce((s,r)=>s+r.debit-r.credit,0))}};};
 const balanceSheet=({asOf='',includeZero=false}={})=>{let rows=raw('',asOf).filter(r=>r.statement==='BalanceSheet').map(r=>{const fs5=balanceSheetClass(r),amount=fs5==='Asset'?r.balance:-r.balance;return{...r,fs5,amount:round(amount)};});if(!includeZero)rows=rows.filter(r=>r.amount);const assets=rows.filter(r=>r.fs5==='Asset'),liabilities=rows.filter(r=>r.fs5==='Liability'),equity=rows.filter(r=>r.fs5==='Equity'),totalAssets=round(assets.reduce((s,r)=>s+r.amount,0)),totalLiabilities=round(liabilities.reduce((s,r)=>s+r.amount,0)),totalEquity=round(equity.reduce((s,r)=>s+r.amount,0)),totalLiabilitiesEquity=round(totalLiabilities+totalEquity);return{companyName,reportName:'Balance Sheet',asOf,sections:[{name:'ASSETS',groups:groupRows(assets)},{name:'LIABILITIES',groups:groupRows(liabilities)},{name:'EQUITY',groups:groupRows(equity)}],totalAssets,totalLiabilities,totalEquity,totalLiabilitiesEquity,difference:round(totalAssets-totalLiabilitiesEquity),balanced:Math.abs(totalAssets-totalLiabilitiesEquity)<.01};};
 const profitLoss=({fromPeriod='',toPeriod='',includeZero=false,view='total'}={})=>{const months=view==='monthly'?monthRange(fromPeriod,toPeriod):[];let rows=raw(fromPeriod,toPeriod).filter(r=>r.statement==='ProfitLoss').map(r=>{const fs5=profitLossClass(r),sign=fs5==='Expense'?-1:1,base=round((r.credit-r.debit)*sign),monthly=Object.fromEntries(months.map(m=>{const x=raw(m,m).find(a=>a.accountCode===r.accountCode),periodClass=profitLossClass(x||r),periodSign=periodClass==='Expense'?-1:1;return[m,round(((x?.credit||0)-(x?.debit||0))*periodSign)];}));return{...r,fs5,amount:base,months:monthly};});if(!includeZero)rows=rows.filter(r=>r.amount||Object.values(r.months).some(Boolean));const revenue=rows.filter(r=>r.fs5==='Revenue'),expenses=rows.filter(r=>r.fs5==='Expense'),totalRevenue=round(revenue.reduce((s,r)=>s+r.amount,0)),totalExpenses=round(expenses.reduce((s,r)=>s+r.amount,0));return{companyName,reportName:'Profit & Loss',fromPeriod,toPeriod,view,months,sections:[{name:'REVENUE',groups:groupRows(revenue)},{name:'EXPENSES',groups:groupRows(expenses)}],rows:[...revenue,...expenses],totalRevenue,totalExpenses,netIncome:round(totalRevenue-totalExpenses)};};
 const cashFlow=({fromPeriod='',toPeriod='',includeZero=false}={})=>{const pl=profitLoss({fromPeriod,toPeriod,includeZero:true});let rows=raw(fromPeriod,toPeriod).filter(r=>r.cashFlowClass!=='None').map(r=>({...r,amount:round(-r.activity)}));if(!includeZero)rows=rows.filter(r=>r.amount);const sections=['Operating','Investing','Financing'].map(name=>({name:`CASH FLOWS FROM ${name.toUpperCase()} ACTIVITIES`,groups:groupRows(rows.filter(r=>r.cashFlowClass===name))})),beginningCash=round(raw('',fromPeriod?previousMonth(fromPeriod):'').filter(r=>r.cashEquivalent).reduce((s,r)=>s+r.balance,0)),endingCash=round(raw('',toPeriod).filter(r=>r.cashEquivalent).reduce((s,r)=>s+r.balance,0)),netChange=round(endingCash-beginningCash);return{companyName,reportName:'Cash Flow Statement',method:'Indirect',fromPeriod,toPeriod,netIncome:pl.netIncome,sections,beginningCash,netChange,endingCash,difference:round(beginningCash+netChange-endingCash),reconciled:Math.abs(beginningCash+netChange-endingCash)<.01};};
 const retainedEarnings=({fromPeriod='',toPeriod=''}={})=>{const beginning=round(raw('',fromPeriod).filter(r=>r.retainedEarnings).reduce((s,r)=>s-r.balance,0)),netIncome=profitLoss({fromPeriod,toPeriod,includeZero:true}).netIncome,distributions=round(raw(fromPeriod,toPeriod).filter(r=>r.distribution).reduce((s,r)=>s+r.debit-r.credit,0)),ending=round(beginning+netIncome-distributions);return{companyName,reportName:'Statement of Retained Earnings',fromPeriod,toPeriod,beginningRetainedEarnings:beginning,netIncome,adjustments:0,distributions,endingRetainedEarnings:ending,reconciled:true,difference:0};};
 return{getPostedAccountActivity:raw,getTrialBalance:trialBalance,getBalanceSheet:balanceSheet,getProfitAndLoss:profitLoss,getCashFlow:cashFlow,getRetainedEarningsStatement:retainedEarnings};
}
