const DAY_MS=86400000;
const nowDate=()=>new Date().toISOString().slice(0,10);
const money=value=>Math.round((Number(value||0)+Number.EPSILON)*100)/100;
const qty=value=>Math.round((Number(value||0)+Number.EPSILON)*1000000)/1000000;
const idNum=value=>Number(String(value||'').replace(/\D/g,''))||0;
const nextId=(prefix,rows)=>`${prefix}-${String(rows.reduce((max,row)=>Math.max(max,idNum(row.id||row.orderNumber||row.planNumber||row.inspectionNumber||row.ncrNumber||row.workOrderNumber)),1000)+1).padStart(4,'0')}`;
const dateMinusDays=(value,days)=>{const d=new Date(`${value||nowDate()}T12:00:00`);d.setDate(d.getDate()-Math.max(0,Number(days||0)));return d.toISOString().slice(0,10);};
const datePlusDays=(value,days)=>{const d=new Date(`${value||nowDate()}T12:00:00`);d.setDate(d.getDate()+Math.max(0,Number(days||0)));return d.toISOString().slice(0,10);};
const activePoStatus=status=>!['Closed','Cancelled','Voided'].includes(String(status||''));
const activeSoStatus=status=>!['Closed','Cancelled','Voided','Completed'].includes(String(status||''));
const activeMfgStatus=status=>!['Closed','Cancelled','Voided'].includes(String(status||''));
const assertPositive=(value,label)=>{const n=Number(value);if(!Number.isFinite(n)||n<=0)throw new Error(`${label} must be greater than zero.`);return n;};

export function createManufacturingRuntime(context={}){
  const itemMaster=context.itemMaster||[],inventoryBalances=context.inventoryBalances||[],inventoryTransactions=context.inventoryTransactions||[],purchaseOrders=context.purchaseOrders||[],purchaseOrderLines=context.purchaseOrderLines||[],vendors=context.vendors||[],salesOrders=context.salesOrders||[],salesOrderLines=context.salesOrderLines||[],warehouses=context.warehouses||[],inventoryLocations=context.inventoryLocations||[];
  const h=context.helpers||{};
  const required=['getBalance','qtyAvail','itemCost','adjustInventoryBalance','createInvAudit','createPostedJournal','periodFromDate','validateInventoryAndGlOpen','calcPoLine','recalcPo','nextPoId'];
  for(const name of required)if(typeof h[name]!=='function')throw new Error(`Manufacturing integration helper ${name} is required.`);

  const settings={rawMaterialAccount:'1507',wipAccount:'1508',finishedGoodsAccount:'1509',laborOverheadAbsorptionAccount:'5101',productionLaborExpenseAccount:'5120',scrapVarianceAccount:'5109',defaultWipWarehouse:'PROD',defaultWipLocation:'PROD-WIP',allowReleaseWithShortage:true,allowNegativeInventory:false,autoBackflush:true,requireQualityBeforeCompletion:false,planningHorizonDays:90,capacityHorizonDays:5};
  const workCenters=[
    {id:'WC-FAB',name:'Fabrication',department:'Manufacturing',warehouse:'PROD',calendar:'Standard',capacityHoursPerDay:16,efficiencyPct:90,laborRatePerHour:32,machineRatePerHour:45,overheadRatePerHour:18,isDown:false,active:true},
    {id:'WC-ASSY',name:'Assembly',department:'Manufacturing',warehouse:'PROD',calendar:'Standard',capacityHoursPerDay:24,efficiencyPct:95,laborRatePerHour:29,machineRatePerHour:8,overheadRatePerHour:15,isDown:false,active:true},
    {id:'WC-QC',name:'Quality Control',department:'Quality',warehouse:'PROD',calendar:'Standard',capacityHoursPerDay:8,efficiencyPct:100,laborRatePerHour:34,machineRatePerHour:0,overheadRatePerHour:10,isDown:false,active:true}
  ];
  const boms=[];
  const routings=[];
  const orders=[];
  const plannedOrders=[];
  const mrpRuns=[];
  const inspections=[];
  const nonconformances=[];
  const maintenanceOrders=[];
  const auditTrail=[];

  function audit(entityType,entityId,action,details='',user='system'){
    const row={id:`MFG-AUD-${String(auditTrail.length+1).padStart(6,'0')}`,entityType,entityId,action,details,user,timestamp:new Date().toISOString()};auditTrail.push(row);return row;
  }
  function item(id){return itemMaster.find(row=>String(row.code)===String(id)||String(row.inventoryId)===String(id));}
  function stockItems(){return itemMaster.filter(row=>row.trackQuantity!==false&&(row.type==='Stock Item'||row.type==='Inventory'));}
  function effectiveRecord(rows,itemId,onDate=nowDate()){
    return rows.filter(row=>row.itemId===itemId&&row.status==='Active'&&(!row.effectiveFrom||row.effectiveFrom<=onDate)&&(!row.effectiveTo||row.effectiveTo>=onDate)).sort((a,b)=>String(b.revision||'').localeCompare(String(a.revision||'')))[0]||null;
  }
  function effectiveBom(itemId,onDate){return effectiveRecord(boms,itemId,onDate);}
  function effectiveRouting(itemId,onDate){return effectiveRecord(routings,itemId,onDate);}
  function normalizeBom(input,existing=null){
    const itemId=String(input.itemId||existing?.itemId||'');if(!item(itemId))throw new Error('Manufactured item is required.');
    const baseQty=assertPositive(input.baseQty??existing?.baseQty??1,'BOM base quantity'),yieldPct=Number(input.yieldPct??existing?.yieldPct??100);if(yieldPct<=0||yieldPct>100)throw new Error('BOM yield percent must be greater than 0 and no more than 100.');
    const components=(input.components||existing?.components||[]).map((line,index)=>{const componentId=String(line.itemId||line.inventoryId||'');if(!item(componentId))throw new Error(`BOM component on line ${index+1} was not found.`);if(componentId===itemId)throw new Error('A BOM cannot contain its own manufactured item as a component.');return{lineId:line.lineId||`L${index+1}`,itemId:componentId,description:item(componentId)?.description||item(componentId)?.name||'',qtyPer:assertPositive(line.qtyPer??line.quantity??0,`Component ${componentId} quantity`),scrapPct:Math.max(0,Number(line.scrapPct||0)),uom:line.uom||item(componentId)?.uom||'EA',supplyType:line.supplyType||'Buy',issueMethod:line.issueMethod||'Backflush',warehouse:line.warehouse||item(componentId)?.defaultWarehouse||'MAIN',location:line.location||item(componentId)?.defaultLocation||'MAIN-A1',alternateGroup:line.alternateGroup||''};});
    if(!components.length)throw new Error('A BOM requires at least one component.');
    return{id:input.id||existing?.id||`BOM-${itemId}-${input.revision||existing?.revision||'A'}`,itemId,description:input.description||existing?.description||`${item(itemId)?.description||itemId} BOM`,revision:String(input.revision||existing?.revision||'A'),status:input.status||existing?.status||'Active',effectiveFrom:input.effectiveFrom||existing?.effectiveFrom||nowDate(),effectiveTo:input.effectiveTo??existing?.effectiveTo??'',baseQty,yieldPct,components,notes:input.notes??existing?.notes??'',updatedAt:new Date().toISOString()};
  }
  function assertNoBomCycle(candidate){
    const map=new Map();for(const row of boms.filter(row=>row.status==='Active'&&row.id!==candidate.id))map.set(row.itemId,row);if(candidate.status==='Active')map.set(candidate.itemId,candidate);
    const walk=(itemId,stack=[])=>{if(stack.includes(itemId))throw new Error(`BOM circular reference detected: ${[...stack,itemId].join(' -> ')}`);const bom=map.get(itemId);if(!bom)return;for(const line of bom.components||[])if(map.has(line.itemId))walk(line.itemId,[...stack,itemId]);};
    walk(candidate.itemId,[]);
  }
  function normalizeRouting(input,existing=null){
    const itemId=String(input.itemId||existing?.itemId||'');if(!item(itemId))throw new Error('Routing item is required.');
    const operations=(input.operations||existing?.operations||[]).map((op,index)=>{const wc=workCenters.find(row=>row.id===(op.workCenterId||op.workCenter));if(!wc)throw new Error(`Work center for operation ${index+1} was not found.`);return{sequence:Number(op.sequence||((index+1)*10)),workCenterId:wc.id,description:op.description||`Operation ${index+1}`,setupHours:Math.max(0,Number(op.setupHours||0)),runHoursPerUnit:Math.max(0,Number(op.runHoursPerUnit||0)),queueHours:Math.max(0,Number(op.queueHours||0)),moveHours:Math.max(0,Number(op.moveHours||0)),laborRate:Number(op.laborRate??wc.laborRatePerHour??0),machineRate:Number(op.machineRate??wc.machineRatePerHour??0),overheadRate:Number(op.overheadRate??wc.overheadRatePerHour??0),qualityCheckpoint:op.qualityCheckpoint===true};}).sort((a,b)=>a.sequence-b.sequence);
    if(!operations.length)throw new Error('A routing requires at least one operation.');if(new Set(operations.map(op=>op.sequence)).size!==operations.length)throw new Error('Routing operation sequences must be unique.');
    return{id:input.id||existing?.id||`RT-${itemId}-${input.revision||existing?.revision||'A'}`,itemId,description:input.description||existing?.description||`${item(itemId)?.description||itemId} Routing`,revision:String(input.revision||existing?.revision||'A'),status:input.status||existing?.status||'Active',effectiveFrom:input.effectiveFrom||existing?.effectiveFrom||nowDate(),effectiveTo:input.effectiveTo??existing?.effectiveTo??'',operations,notes:input.notes??existing?.notes??'',updatedAt:new Date().toISOString()};
  }
  function materialRequirements(bom,productionQty){
    const yieldFactor=Math.max(0.000001,Number(bom.yieldPct||100)/100);return (bom.components||[]).map(line=>{const required=Number(productionQty)*Number(line.qtyPer||0)/Number(bom.baseQty||1)/yieldFactor*(1+Number(line.scrapPct||0)/100);return{lineId:line.lineId,itemId:line.itemId,description:line.description,requiredQty:qty(required),qtyReserved:0,qtyIssued:0,shortageQty:0,uom:line.uom,supplyType:line.supplyType,issueMethod:line.issueMethod,warehouse:line.warehouse,location:line.location,unitCost:money(h.itemCost(item(line.itemId))),extendedRequiredCost:money(required*h.itemCost(item(line.itemId)))};});
  }
  function operationPlan(routing,productionQty){return(routing?.operations||[]).map(op=>{const wc=workCenters.find(row=>row.id===op.workCenterId)||{};const runHours=Number(op.runHoursPerUnit||0)*Number(productionQty);return{...op,workCenterName:wc.name||op.workCenterId,plannedSetupHours:Number(op.setupHours||0),plannedRunHours:runHours,plannedTotalHours:Number(op.setupHours||0)+runHours,actualLaborHours:0,actualMachineHours:0,qtyGood:0,qtyScrap:0,status:'Pending',startedAt:'',completedAt:'',laborCost:0,machineCost:0,overheadCost:0};});}
  function createOrder(input={},user='system'){
    const itemId=String(input.itemId||input.inventoryId||'');const manufacturedItem=item(itemId);if(!manufacturedItem)throw new Error('Manufactured item was not found.');const quantity=assertPositive(input.quantity??input.qty??0,'Production quantity');const dueDate=input.dueDate||datePlusDays(nowDate(),Math.max(1,Number(manufacturedItem.leadTimeDays||7)));const bom=(input.bomId?boms.find(row=>row.id===input.bomId):effectiveBom(itemId,input.startDate||nowDate()));if(!bom)throw new Error(`No active BOM exists for ${itemId}.`);const routing=(input.routingId?routings.find(row=>row.id===input.routingId):effectiveRouting(itemId,input.startDate||nowDate()));
    const id=input.id||nextId('MO',orders);const row={id,orderNumber:id,itemId,description:manufacturedItem.description||manufacturedItem.name||itemId,quantity:qty(quantity),qtyCompleted:0,qtyScrapped:0,status:'Planned',priority:input.priority||'Normal',startDate:input.startDate||nowDate(),dueDate,bomId:bom.id,bomRevision:bom.revision,routingId:routing?.id||'',routingRevision:routing?.revision||'',wipWarehouse:input.wipWarehouse||settings.defaultWipWarehouse,wipLocation:input.wipLocation||settings.defaultWipLocation,outputWarehouse:input.outputWarehouse||manufacturedItem.defaultWarehouse||'MAIN',outputLocation:input.outputLocation||manufacturedItem.defaultLocation||'MAIN-A1',sourceType:input.sourceType||'Manual',sourceReference:input.sourceReference||'',salesOrderId:input.salesOrderId||'',customerId:input.customerId||'',materials:materialRequirements(bom,quantity),operations:operationPlan(routing,quantity),materialShortage:false,qualityHold:false,costs:{material:0,labor:0,machine:0,overhead:0,scrap:0,finishedGoods:0,variance:0},journalReferences:[],createdAt:new Date().toISOString(),createdBy:user,updatedAt:new Date().toISOString()};orders.push(row);audit('Production Order',row.id,'Created',`${row.itemId} x ${row.quantity}`,user);return row;
  }
  function releaseReservations(order){for(const line of order.materials||[]){if(Number(line.qtyReserved||0)>0){h.adjustInventoryBalance({itemId:line.itemId,warehouse:line.warehouse,location:line.location,allocatedDelta:-Number(line.qtyReserved||0)});line.qtyReserved=0;line.shortageQty=Math.max(0,Number(line.requiredQty||0)-Number(line.qtyIssued||0));}}}
  function reserveMaterials(order){let hasShortage=false;for(const line of order.materials||[]){const remaining=Math.max(0,Number(line.requiredQty||0)-Number(line.qtyIssued||0)-Number(line.qtyReserved||0));if(remaining<=0){line.shortageQty=0;continue;}const balance=h.getBalance(line.itemId,line.warehouse,line.location);const available=Math.max(0,Number(h.qtyAvail(balance)||0));const reserve=Math.min(remaining,available);if(reserve>0){h.adjustInventoryBalance({itemId:line.itemId,warehouse:line.warehouse,location:line.location,allocatedDelta:reserve});line.qtyReserved=qty(Number(line.qtyReserved||0)+reserve);}line.shortageQty=qty(Math.max(0,remaining-reserve));if(line.shortageQty>0)hasShortage=true;}order.materialShortage=hasShortage;return !hasShortage;}
  function releaseOrder(order,user='system'){
    if(!['Planned','Material Shortage'].includes(order.status))throw new Error('Only planned production orders can be released.');const sufficient=reserveMaterials(order);if(!sufficient&&!settings.allowReleaseWithShortage){releaseReservations(order);throw new Error('Production order has material shortages and release-with-shortage is disabled.');}order.status=sufficient?'Released':'Material Shortage';order.releasedAt=new Date().toISOString();order.updatedAt=order.releasedAt;audit('Production Order',order.id,'Released',sufficient?'Materials reserved.':'Released with material shortages.',user);return order;
  }
  function postJournal(order,description,lines,user){if(!lines.length)return'';const postDate=nowDate(),period=h.periodFromDate(postDate);h.validateInventoryAndGlOpen(period);const je=h.createPostedJournal({module:'Manufacturing',description,postPeriod:period,transactionDate:postDate,sourceRef:order.id,lines,createdBy:user});const ref=je?.jeNumber||je?.id||String(je||'');if(ref)order.journalReferences.push(ref);return ref;}
  function issueMaterials(order,input={},user='system'){
    if(!['Released','Material Shortage','In Process'].includes(order.status))throw new Error('Release the production order before issuing materials.');const requested=Array.isArray(input.lines)&&input.lines.length?input.lines:null;const issueList=[];
    for(const line of order.materials||[]){const req=requested?.find(row=>String(row.itemId||row.inventoryId)===String(line.itemId));if(requested&&!req)continue;const remaining=Math.max(0,Number(line.requiredQty||0)-Number(line.qtyIssued||0));const issueQty=qty(Math.min(remaining,Math.max(0,Number(req?.quantity??req?.qty??remaining))));if(issueQty<=0)continue;issueList.push({line,issueQty});}
    if(!issueList.length)throw new Error('No material quantity remains to issue.');const journalLines=[],auditRows=[];for(const entry of issueList){const line=entry.line,issueQty=entry.issueQty,balance=h.getBalance(line.itemId,line.warehouse,line.location),available=settings.allowNegativeInventory?Number.POSITIVE_INFINITY:Number(balance.qtyOnHand||0);if(available+0.000001<issueQty)throw new Error(`Insufficient on-hand quantity for ${line.itemId}. Required ${issueQty}, on hand ${Number(balance.qtyOnHand||0)}.`);const unitCost=Number(balance.averageCost||h.itemCost(item(line.itemId))||0),amount=money(issueQty*unitCost),releaseReserved=Math.min(Number(line.qtyReserved||0),issueQty);h.adjustInventoryBalance({itemId:line.itemId,warehouse:line.warehouse,location:line.location,qtyOut:issueQty,allocatedDelta:-releaseReserved});line.qtyReserved=qty(Math.max(0,Number(line.qtyReserved||0)-releaseReserved));line.qtyIssued=qty(Number(line.qtyIssued||0)+issueQty);line.shortageQty=qty(Math.max(0,Number(line.requiredQty||0)-Number(line.qtyIssued||0)-Number(line.qtyReserved||0)));journalLines.push({account:settings.wipAccount,debit:amount,credit:0,description:`WIP material ${line.itemId}`,sourceReference:order.id},{account:item(line.itemId)?.inventoryAccount||settings.rawMaterialAccount,debit:0,credit:amount,description:`Material issue ${line.itemId}`,sourceReference:order.id});auditRows.push({line,issueQty,unitCost,amount});order.costs.material=money(Number(order.costs.material||0)+amount);}
    const jeRef=postJournal(order,`Manufacturing material issue ${order.id}`,journalLines,user);for(const row of auditRows)h.createInvAudit({transactionType:'Production Material Issue',referenceNumber:order.id,sourceModule:'Manufacturing',sourceReference:order.id,itemId:row.line.itemId,warehouse:row.line.warehouse,location:row.line.location,quantityOut:row.issueQty,unitCost:row.unitCost,postDate:nowDate(),postPeriod:h.periodFromDate(nowDate()),jeReference:jeRef,createdBy:user});order.materialShortage=(order.materials||[]).some(line=>Number(line.shortageQty||0)>0);order.status='In Process';order.updatedAt=new Date().toISOString();audit('Production Order',order.id,'Material Issue',`${issueList.length} component line(s) issued.`,user);return{order,jeReference:jeRef};
  }
  function operationCost(op,input){const wc=workCenters.find(row=>row.id===op.workCenterId)||{};const laborHours=Math.max(0,Number(input.laborHours||0)),machineHours=Math.max(0,Number(input.machineHours||0)),laborRate=Number(input.laborRate??op.laborRate??wc.laborRatePerHour??0),machineRate=Number(input.machineRate??op.machineRate??wc.machineRatePerHour??0),overheadRate=Number(input.overheadRate??op.overheadRate??wc.overheadRatePerHour??0),overheadHours=Math.max(laborHours,machineHours);return{laborHours,machineHours,laborCost:money(laborHours*laborRate),machineCost:money(machineHours*machineRate),overheadCost:money(overheadHours*overheadRate)};}
  function reportOperation(order,input={},user='system'){
    if(!['Released','Material Shortage','In Process'].includes(order.status))throw new Error('Release the production order before reporting operations.');const sequence=Number(input.sequence);const op=(order.operations||[]).find(row=>Number(row.sequence)===sequence);if(!op)throw new Error('Production operation was not found.');const wc=workCenters.find(row=>row.id===op.workCenterId);if(wc?.isDown)throw new Error(`${wc.name||wc.id} is down for maintenance.`);const c=operationCost(op,input),total=money(c.laborCost+c.machineCost+c.overheadCost);if(total>0){const jeRef=postJournal(order,`Manufacturing operation ${order.id} / ${sequence}`,[{account:settings.wipAccount,debit:total,credit:0,description:`WIP operation ${sequence}`,sourceReference:order.id},{account:settings.laborOverheadAbsorptionAccount,debit:0,credit:total,description:`Labor/machine/overhead absorption ${sequence}`,sourceReference:order.id}],user);op.lastJeReference=jeRef;}
    op.actualLaborHours=qty(Number(op.actualLaborHours||0)+c.laborHours);op.actualMachineHours=qty(Number(op.actualMachineHours||0)+c.machineHours);op.laborCost=money(Number(op.laborCost||0)+c.laborCost);op.machineCost=money(Number(op.machineCost||0)+c.machineCost);op.overheadCost=money(Number(op.overheadCost||0)+c.overheadCost);op.qtyGood=qty(Number(op.qtyGood||0)+Math.max(0,Number(input.qtyGood||0)));op.qtyScrap=qty(Number(op.qtyScrap||0)+Math.max(0,Number(input.qtyScrap||0)));if(!op.startedAt)op.startedAt=new Date().toISOString();if(op.qtyGood+op.qtyScrap+0.000001>=order.quantity){op.status='Completed';op.completedAt=new Date().toISOString();}else op.status='In Process';order.costs.labor=money(Number(order.costs.labor||0)+c.laborCost);order.costs.machine=money(Number(order.costs.machine||0)+c.machineCost);order.costs.overhead=money(Number(order.costs.overhead||0)+c.overheadCost);order.status='In Process';order.updatedAt=new Date().toISOString();audit('Production Order',order.id,'Operation Reported',`Operation ${sequence}: labor ${c.laborHours}h, machine ${c.machineHours}h.`,user);return order;
  }
  function inspectionAcceptedQty(order,sequence){return inspections.filter(row=>row.productionOrderId===order.id&&Number(row.operationSequence)===Number(sequence)&&row.result==='Pass').reduce((sum,row)=>sum+Number(row.qtyAccepted||0),0);}
  function ensureQualityGate(order,newCompleted){if(order.qualityHold)throw new Error('Production order is on quality hold. Resolve open nonconformance records before completion.');if(!settings.requireQualityBeforeCompletion)return;for(const op of order.operations||[]){if(op.qualityCheckpoint&&inspectionAcceptedQty(order,op.sequence)+0.000001<newCompleted)throw new Error(`Quality inspection is required for operation ${op.sequence} before completing ${newCompleted} units.`);}}
  function backflush(order,newProgress,user){if(!settings.autoBackflush)return;const lines=[];for(const line of order.materials||[]){if(line.issueMethod!=='Backflush')continue;const target=qty(Number(line.requiredQty||0)*Math.min(1,newProgress/Math.max(0.000001,Number(order.quantity||0))));const need=qty(Math.max(0,target-Number(line.qtyIssued||0)));if(need>0)lines.push({itemId:line.itemId,quantity:need});}if(lines.length)issueMaterials(order,{lines},user);}
  function wipAdded(order){return money(Number(order.costs.material||0)+Number(order.costs.labor||0)+Number(order.costs.machine||0)+Number(order.costs.overhead||0));}
  function wipRelieved(order){return money(Number(order.costs.finishedGoods||0)+Number(order.costs.scrap||0)+Number(order.costs.variance||0));}
  function completeOrder(order,input={},user='system'){
    if(!['Released','Material Shortage','In Process','Completed'].includes(order.status))throw new Error('Release the production order before reporting completion.');const remaining=Math.max(0,Number(order.quantity||0)-Number(order.qtyCompleted||0)-Number(order.qtyScrapped||0));const completed=assertPositive(input.quantity??input.qtyCompleted??remaining,'Completed quantity'),scrapped=Math.max(0,Number(input.scrapQty||0));if(completed+scrapped>remaining+0.000001)throw new Error('Completion and scrap quantities exceed the remaining production order quantity.');const projectedCompleted=Number(order.qtyCompleted||0)+completed;ensureQualityGate(order,projectedCompleted);backflush(order,Number(order.qtyCompleted||0)+Number(order.qtyScrapped||0)+completed+scrapped,user);
    const manufacturedItem=item(order.itemId),availableWip=money(wipAdded(order)-wipRelieved(order));if(availableWip<=0)throw new Error('No WIP cost is available. Issue materials or report production operations before completing finished goods.');const totalRemainingBefore=Math.max(0.000001,remaining),standardUnit=Math.max(0,Number(manufacturedItem?.standardCost||manufacturedItem?.cost||0));const proportional=money(availableWip*(completed/totalRemainingBefore));const standardValue=money(standardUnit*completed);const receiptValue=money(Math.min(availableWip,manufacturedItem?.costingMethod==='Standard Cost'&&standardValue>0?standardValue:proportional));if(receiptValue<=0)throw new Error('Finished goods completion value must be greater than zero.');const unitCost=money(receiptValue/completed);const period=h.periodFromDate(nowDate());h.validateInventoryAndGlOpen(period);const fgAccount=manufacturedItem?.manufacturingInventoryAccount||settings.finishedGoodsAccount;const jeRef=postJournal(order,`Manufacturing completion ${order.id}`,[{account:fgAccount,debit:receiptValue,credit:0,description:`Finished goods ${order.itemId}`,sourceReference:order.id},{account:settings.wipAccount,debit:0,credit:receiptValue,description:`WIP relief ${order.id}`,sourceReference:order.id}],user);h.adjustInventoryBalance({itemId:order.itemId,warehouse:order.outputWarehouse,location:order.outputLocation,qtyIn:completed,unitCost});h.createInvAudit({transactionType:'Production Receipt',referenceNumber:order.id,sourceModule:'Manufacturing',sourceReference:order.id,itemId:order.itemId,warehouse:order.outputWarehouse,location:order.outputLocation,quantityIn:completed,unitCost,postDate:nowDate(),postPeriod:period,jeReference:jeRef,createdBy:user});order.costs.finishedGoods=money(Number(order.costs.finishedGoods||0)+receiptValue);order.qtyCompleted=qty(Number(order.qtyCompleted||0)+completed);
    if(scrapped>0){const wipAfterFg=Math.max(0,money(wipAdded(order)-wipRelieved(order)));const scrapValue=money(Math.min(wipAfterFg,(standardUnit>0?standardUnit:unitCost)*scrapped));if(scrapValue>0){postJournal(order,`Manufacturing scrap ${order.id}`,[{account:settings.scrapVarianceAccount,debit:scrapValue,credit:0,description:`Production scrap ${order.itemId}`,sourceReference:order.id},{account:settings.wipAccount,debit:0,credit:scrapValue,description:`WIP scrap relief ${order.id}`,sourceReference:order.id}],user);order.costs.scrap=money(Number(order.costs.scrap||0)+scrapValue);}order.qtyScrapped=qty(Number(order.qtyScrapped||0)+scrapped);}
    const finished=Number(order.qtyCompleted||0)+Number(order.qtyScrapped||0)+0.000001>=Number(order.quantity||0);order.status=finished?'Completed':'In Process';if(finished){releaseReservations(order);order.completedAt=new Date().toISOString();}order.updatedAt=new Date().toISOString();audit('Production Order',order.id,'Completion',`${completed} completed${scrapped?`, ${scrapped} scrapped`:''}.`,user);return order;
  }
  function closeOrder(order,user='system'){
    if(order.status!=='Completed')throw new Error('Only completed production orders can be closed.');releaseReservations(order);const residual=money(wipAdded(order)-wipRelieved(order));if(Math.abs(residual)>=0.01){const lines=residual>0?[{account:settings.scrapVarianceAccount,debit:Math.abs(residual),credit:0,description:`Manufacturing close variance ${order.id}`,sourceReference:order.id},{account:settings.wipAccount,debit:0,credit:Math.abs(residual),description:`Clear WIP ${order.id}`,sourceReference:order.id}]:[{account:settings.wipAccount,debit:Math.abs(residual),credit:0,description:`Restore WIP ${order.id}`,sourceReference:order.id},{account:settings.scrapVarianceAccount,debit:0,credit:Math.abs(residual),description:`Manufacturing close variance ${order.id}`,sourceReference:order.id}];postJournal(order,`Manufacturing close ${order.id}`,lines,user);order.costs.variance=money(Number(order.costs.variance||0)+residual);}order.status='Closed';order.closedAt=new Date().toISOString();order.updatedAt=order.closedAt;audit('Production Order',order.id,'Closed',`Residual WIP variance ${money(residual)}.`,user);return order;
  }
  function cancelOrder(order,user='system'){
    if(['Closed','Cancelled'].includes(order.status))throw new Error('Production order is already closed or cancelled.');if(wipAdded(order)>0||Number(order.qtyCompleted||0)>0||Number(order.qtyScrapped||0)>0)throw new Error('A production order with posted production activity cannot be cancelled. Complete and close it instead.');releaseReservations(order);order.status='Cancelled';order.updatedAt=new Date().toISOString();audit('Production Order',order.id,'Cancelled','No posted production activity existed.',user);return order;
  }
  function roundPlanQuantity(itemRow,value){let result=Math.max(0,Number(value||0));const min=Number(itemRow?.minimumOrderQty||0),multiple=Math.max(1,Number(itemRow?.orderMultiple||1));if(result>0&&min>0)result=Math.max(result,min);return result>0?qty(Math.ceil(result/multiple)*multiple):0;}
  function supplyFor(itemId){const onHand=inventoryBalances.filter(row=>row.itemId===itemId).reduce((sum,row)=>sum+Math.max(0,Number(row.qtyOnHand||0)-Number(row.qtyAllocated||0)),0),openPo=purchaseOrderLines.filter(line=>line.inventoryId===itemId&&activePoStatus(purchaseOrders.find(po=>po.id===line.poId)?.status)).reduce((sum,line)=>sum+Math.max(0,Number(line.qtyOpen??(Number(line.qtyOrdered||0)-Number(line.qtyReceived||0)-Number(line.qtyCancelled||0)))),0),openMfg=orders.filter(order=>order.itemId===itemId&&activeMfgStatus(order.status)).reduce((sum,order)=>sum+Math.max(0,Number(order.quantity||0)-Number(order.qtyCompleted||0)-Number(order.qtyScrapped||0)),0);return qty(onHand+openPo+openMfg);}
  function salesDemand(){const rows=[];for(const line of salesOrderLines){const so=salesOrders.find(order=>order.id===line.salesOrderId||order.orderNumber===line.salesOrderId)||{};if(!activeSoStatus(so.status))continue;const itemId=line.inventoryId||line.itemId;if(!item(itemId))continue;const outstanding=Math.max(0,Number(line.qtyOrdered??line.quantity??0)-Number(line.qtyShipped||0)-Number(line.qtyCancelled||0));if(outstanding<=0)continue;rows.push({itemId,quantity:qty(outstanding),sourceType:'Sales Order',sourceReference:so.orderNumber||so.id||line.salesOrderId||'',dueDate:so.requestedDate||so.shipDate||so.dueDate||datePlusDays(nowDate(),7)});}return rows;}
  function runMrp(input={},user='system'){
    plannedOrders.filter(row=>row.status==='Suggested').forEach(row=>row.status='Superseded');const demands=salesDemand();for(const extra of input.demands||[]){if(extra.itemId&&Number(extra.quantity)>0)demands.push({itemId:extra.itemId,quantity:Number(extra.quantity),sourceType:extra.sourceType||'Manual Demand',sourceReference:extra.sourceReference||'',dueDate:extra.dueDate||datePlusDays(nowDate(),7)});}const supplyRemaining=new Map(stockItems().map(row=>[row.code,supplyFor(row.code)])),planMap=new Map();
    const addPlan=(type,itemId,quantity,dueDate,source)=>{const key=`${type}|${itemId}|${dueDate}`;let plan=planMap.get(key);if(!plan){const itemRow=item(itemId);plan={id:'',planNumber:'',type,itemId,description:itemRow?.description||itemRow?.name||itemId,quantity:0,dueDate,releaseDate:dateMinusDays(dueDate,itemRow?.leadTimeDays||0),status:'Suggested',sourceDemands:[],suggestedVendor:itemRow?.preferredVendor||'',linkedProductionOrder:'',linkedPurchaseOrder:'',createdAt:new Date().toISOString()};planMap.set(key,plan);}plan.quantity=qty(plan.quantity+quantity);plan.sourceDemands.push(source);};
    const planNeed=(itemId,gross,dueDate,source,stack=[])=>{if(stack.includes(itemId))throw new Error(`MRP encountered a circular BOM: ${[...stack,itemId].join(' -> ')}`);const current=Number(supplyRemaining.get(itemId)||0),used=Math.min(current,gross);supplyRemaining.set(itemId,qty(current-used));let short=Math.max(0,gross-used);if(short<=0)return;const itemRow=item(itemId);short=roundPlanQuantity(itemRow,short);const bom=effectiveBom(itemId,nowDate());if(bom){addPlan('Make',itemId,short,dueDate,source);for(const component of materialRequirements(bom,short)){planNeed(component.itemId,component.requiredQty,dueDate,{sourceType:'BOM Demand',sourceReference:itemId,parentSource:source},[...stack,itemId]);}}else addPlan('Buy',itemId,short,dueDate,source);};
    const grouped=new Map();for(const demand of demands){const row=grouped.get(demand.itemId)||{quantity:0,dueDate:demand.dueDate,sources:[]};row.quantity+=Number(demand.quantity||0);if(demand.dueDate<row.dueDate)row.dueDate=demand.dueDate;row.sources.push(demand);grouped.set(demand.itemId,row);}for(const [itemId,row] of grouped){const safety=Math.max(0,Number(item(itemId)?.safetyStock||0));planNeed(itemId,row.quantity+safety,row.dueDate,{sourceType:'Demand',sourceReference:row.sources.map(x=>x.sourceReference).filter(Boolean).join(', '),details:row.sources});}
    const created=[];for(const plan of planMap.values()){plan.quantity=roundPlanQuantity(item(plan.itemId),plan.quantity);plan.id=nextId('MPLN',[...plannedOrders,...created]);plan.planNumber=plan.id;plannedOrders.push(plan);created.push(plan);}const run={id:nextId('MRP',mrpRuns),runNumber:'',runDate:new Date().toISOString(),demandCount:demands.length,plannedCount:created.length,makeCount:created.filter(row=>row.type==='Make').length,buyCount:created.filter(row=>row.type==='Buy').length,user};run.runNumber=run.id;mrpRuns.push(run);audit('MRP Run',run.id,'Completed',`${run.plannedCount} planned order(s) created.`,user);return{run,plannedOrders:created,demands};
  }
  function convertPlan(plan,user='system'){
    if(plan.status!=='Suggested')throw new Error('Only suggested planned orders can be converted.');if(plan.type==='Make'){const order=createOrder({itemId:plan.itemId,quantity:plan.quantity,dueDate:plan.dueDate,sourceType:'MRP',sourceReference:plan.id},user);plan.status='Converted';plan.linkedProductionOrder=order.id;return{type:'Production Order',productionOrder:order,plannedOrder:plan};}
    const itemRow=item(plan.itemId),vendorId=plan.suggestedVendor||itemRow?.preferredVendor,vendor=vendors.find(row=>row.id===vendorId);if(!vendor)throw new Error(`Preferred vendor is required to convert planned purchase for ${plan.itemId}.`);const poId=h.nextPoId('PO',purchaseOrders),today=nowDate(),po={id:poId,poNumber:poId,poType:'RO',status:'Saved',orderDate:today,requestedDate:plan.dueDate,promisedDate:'',postDate:today,postPeriod:h.periodFromDate(today),vendorId:vendor.id,vendorName:vendor.name,vendorLocation:'MAIN',branch:'100',warehouse:itemRow?.defaultWarehouse||'MAIN',currency:vendor.currency||'USD',terms:vendor.terms||'NET30',buyer:'BUYER-01',shipVia:'Best Way',fobPoint:'Destination',vendorRef:'',description:`Created from MRP ${plan.id}`,freight:0,prepaymentRequired:0,sourceManufacturingPlan:plan.id};purchaseOrders.push(po);purchaseOrderLines.push(h.calcPoLine({inventoryId:plan.itemId,qtyOrdered:plan.quantity,unitCost:itemRow?.lastCost||h.itemCost(itemRow),warehouse:itemRow?.defaultWarehouse||'MAIN',location:itemRow?.defaultLocation||'MAIN-A1',requestedDate:plan.dueDate},0,poId));h.recalcPo(po);plan.status='Converted';plan.linkedPurchaseOrder=poId;audit('Planned Order',plan.id,'Converted',`Purchase order ${poId} created.`,user);return{type:'Purchase Order',purchaseOrder:po,plannedOrder:plan};
  }
  function createInspection(input={},user='system'){
    const order=orders.find(row=>row.id===input.productionOrderId||row.orderNumber===input.productionOrderId);if(!order)throw new Error('Production order is required for inspection.');const inspected=assertPositive(input.qtyInspected??input.quantity??0,'Inspected quantity'),accepted=Math.max(0,Number(input.qtyAccepted??(input.result==='Pass'?inspected:0))),rejected=Math.max(0,Number(input.qtyRejected??(inspected-accepted)));if(accepted+rejected>inspected+0.000001)throw new Error('Accepted plus rejected quantity cannot exceed inspected quantity.');const result=input.result||((rejected>0)?'Fail':'Pass'),row={id:nextId('INSP',inspections),inspectionNumber:'',productionOrderId:order.id,itemId:order.itemId,operationSequence:Number(input.operationSequence||0),inspectionType:input.inspectionType||'In Process',qtyInspected:inspected,qtyAccepted:accepted,qtyRejected:rejected,result,measurements:Array.isArray(input.measurements)?input.measurements:[],notes:input.notes||'',inspector:user,inspectionDate:new Date().toISOString()};row.inspectionNumber=row.id;inspections.push(row);if(result==='Fail'||rejected>0){order.qualityHold=true;const ncr={id:nextId('NCR',nonconformances),ncrNumber:'',productionOrderId:order.id,inspectionId:row.id,itemId:order.itemId,operationSequence:row.operationSequence,qtyRejected:rejected||inspected,status:'Open',disposition:'',reason:input.failureReason||input.notes||'Quality inspection failed',createdAt:new Date().toISOString(),closedAt:''};ncr.ncrNumber=ncr.id;nonconformances.push(ncr);audit('Nonconformance',ncr.id,'Created',ncr.reason,user);}audit('Quality Inspection',row.id,'Recorded',`${result}: ${inspected} inspected.`,user);return row;
  }
  function dispositionNcr(ncr,input={},user='system'){
    if(ncr.status==='Closed')throw new Error('Nonconformance is already closed.');const disposition=input.disposition||'';if(!['Rework','Scrap','Use As Is','Return to Vendor'].includes(disposition))throw new Error('A valid nonconformance disposition is required.');ncr.disposition=disposition;ncr.dispositionNotes=input.notes||'';ncr.status='Closed';ncr.closedAt=new Date().toISOString();ncr.closedBy=user;const order=orders.find(row=>row.id===ncr.productionOrderId);if(order&&!nonconformances.some(row=>row.productionOrderId===order.id&&row.status==='Open'))order.qualityHold=false;audit('Nonconformance',ncr.id,'Disposed',disposition,user);return ncr;
  }
  function upsertWorkCenter(input={},user='system'){
    const existing=workCenters.find(row=>row.id===input.id);const row={id:input.id||nextId('WC',workCenters),name:input.name||existing?.name||'',department:input.department||existing?.department||'Manufacturing',warehouse:input.warehouse||existing?.warehouse||settings.defaultWipWarehouse,calendar:input.calendar||existing?.calendar||'Standard',capacityHoursPerDay:Math.max(0,Number(input.capacityHoursPerDay??existing?.capacityHoursPerDay??8)),efficiencyPct:Math.max(1,Number(input.efficiencyPct??existing?.efficiencyPct??100)),laborRatePerHour:Math.max(0,Number(input.laborRatePerHour??existing?.laborRatePerHour??0)),machineRatePerHour:Math.max(0,Number(input.machineRatePerHour??existing?.machineRatePerHour??0)),overheadRatePerHour:Math.max(0,Number(input.overheadRatePerHour??existing?.overheadRatePerHour??0)),isDown:input.isDown??existing?.isDown??false,active:input.active??existing?.active??true};if(!row.name)throw new Error('Work center name is required.');if(existing)Object.assign(existing,row);else workCenters.push(row);audit('Work Center',row.id,existing?'Updated':'Created',row.name,user);return existing||row;
  }
  function createMaintenance(input={},user='system'){
    const wc=workCenters.find(row=>row.id===input.workCenterId);if(!wc)throw new Error('Work center is required.');const row={id:nextId('MWO',maintenanceOrders),workOrderNumber:'',workCenterId:wc.id,workCenterName:wc.name,type:input.type||'Corrective',priority:input.priority||'Normal',description:input.description||'',scheduledDate:input.scheduledDate||nowDate(),status:input.status||'Open',downtimeHours:Math.max(0,Number(input.downtimeHours||0)),notes:input.notes||'',createdAt:new Date().toISOString(),createdBy:user,completedAt:''};row.workOrderNumber=row.id;maintenanceOrders.push(row);if(row.status==='In Progress')wc.isDown=true;audit('Maintenance Work Order',row.id,'Created',row.description,user);return row;
  }
  function setMaintenanceStatus(row,status,user='system'){
    if(!['Open','Scheduled','In Progress','Completed','Cancelled'].includes(status))throw new Error('Invalid maintenance status.');row.status=status;const wc=workCenters.find(x=>x.id===row.workCenterId);if(wc){if(status==='In Progress')wc.isDown=true;if(['Completed','Cancelled'].includes(status)&&!maintenanceOrders.some(x=>x.id!==row.id&&x.workCenterId===wc.id&&x.status==='In Progress'))wc.isDown=false;}if(status==='Completed')row.completedAt=new Date().toISOString();audit('Maintenance Work Order',row.id,'Status Changed',status,user);return row;
  }
  function capacityReport(horizonDays=settings.capacityHorizonDays){const days=Math.max(1,Number(horizonDays||5));return workCenters.filter(wc=>wc.active!==false).map(wc=>{const ordersLoad=orders.filter(order=>activeMfgStatus(order.status)).flatMap(order=>(order.operations||[]).filter(op=>op.workCenterId===wc.id&&op.status!=='Completed').map(op=>Math.max(0,Number(op.plannedTotalHours||0)-Number(op.actualLaborHours||0)-Number(op.actualMachineHours||0)))).reduce((sum,n)=>sum+n,0),capacity=wc.isDown?0:Number(wc.capacityHoursPerDay||0)*(Number(wc.efficiencyPct||100)/100)*days;return{workCenterId:wc.id,workCenterName:wc.name,isDown:wc.isDown,horizonDays:days,capacityHours:qty(capacity),loadHours:qty(ordersLoad),availableHours:qty(capacity-ordersLoad),utilizationPct:capacity>0?money(ordersLoad/capacity*100):(ordersLoad>0?999:0),status:wc.isDown?'Down':ordersLoad>capacity?'Over Capacity':ordersLoad>capacity*.85?'Near Capacity':'Available'};});}
  function wipReport(){return orders.filter(order=>!['Planned','Cancelled','Closed'].includes(order.status)).map(order=>({orderNumber:order.id,itemId:order.itemId,description:order.description,status:order.status,quantity:order.quantity,qtyCompleted:order.qtyCompleted,materialCost:money(order.costs.material),laborCost:money(order.costs.labor),machineCost:money(order.costs.machine),overheadCost:money(order.costs.overhead),wipAdded:wipAdded(order),wipRelieved:wipRelieved(order),wipBalance:money(wipAdded(order)-wipRelieved(order)),dueDate:order.dueDate,materialShortage:order.materialShortage,qualityHold:order.qualityHold}));}
  function varianceReport(){return orders.filter(order=>['Completed','Closed'].includes(order.status)).map(order=>{const itemRow=item(order.itemId),actualCost=money(wipAdded(order)),actualUnit=Number(order.qtyCompleted||0)>0?money(actualCost/Number(order.qtyCompleted)):0,standardUnit=money(itemRow?.standardCost||itemRow?.cost||0),standardTotal=money(standardUnit*Number(order.qtyCompleted||0));return{orderNumber:order.id,itemId:order.itemId,status:order.status,qtyCompleted:order.qtyCompleted,actualCost,actualUnitCost:actualUnit,standardUnitCost:standardUnit,standardCost:standardTotal,variance:money(actualCost-standardTotal),closeVariance:money(order.costs.variance||0)};});}
  function shortageReport(){return orders.flatMap(order=>(order.materials||[]).filter(line=>Number(line.shortageQty||0)>0).map(line=>({orderNumber:order.id,status:order.status,dueDate:order.dueDate,parentItem:order.itemId,componentItem:line.itemId,description:line.description,requiredQty:line.requiredQty,reservedQty:line.qtyReserved,issuedQty:line.qtyIssued,shortageQty:line.shortageQty,warehouse:line.warehouse,location:line.location,preferredVendor:item(line.itemId)?.preferredVendor||''})));}
  function productionReport(){return orders.map(order=>({orderNumber:order.id,itemId:order.itemId,description:order.description,status:order.status,priority:order.priority,sourceType:order.sourceType,sourceReference:order.sourceReference,quantity:order.quantity,qtyCompleted:order.qtyCompleted,qtyScrapped:order.qtyScrapped,completionPct:money((Number(order.qtyCompleted||0)+Number(order.qtyScrapped||0))/Math.max(1,Number(order.quantity||0))*100),startDate:order.startDate,dueDate:order.dueDate,materialShortage:order.materialShortage,qualityHold:order.qualityHold,totalActualCost:wipAdded(order),finishedGoodsValue:money(order.costs.finishedGoods),variance:money(order.costs.variance)}));}
  function overview(){const active=orders.filter(order=>activeMfgStatus(order.status)&&order.status!=='Planned'),wip=wipReport(),capacity=capacityReport();return{asOf:new Date().toISOString(),kpis:{activeOrders:active.length,plannedOrders:orders.filter(o=>o.status==='Planned').length,mrpSuggestions:plannedOrders.filter(p=>p.status==='Suggested').length,materialShortages:shortageReport().length,openQualityIssues:nonconformances.filter(n=>n.status==='Open').length,workCentersDown:workCenters.filter(w=>w.isDown).length,wipValue:money(wip.reduce((sum,row)=>sum+row.wipBalance,0)),overdueOrders:active.filter(o=>o.dueDate&&o.dueDate<nowDate()).length},activeOrders:productionReport().filter(row=>!['Closed','Cancelled'].includes(row.status)).slice(0,25),shortages:shortageReport().slice(0,25),capacity};}
  function serializeOrder(order){return{...order,wipAdded:wipAdded(order),wipRelieved:wipRelieved(order),wipBalance:money(wipAdded(order)-wipRelieved(order)),actualTotalCost:wipAdded(order),standardTotalCost:money((item(order.itemId)?.standardCost||item(order.itemId)?.cost||0)*Number(order.qtyCompleted||0))};}
  function referenceData(){return{items:stockItems().map(row=>({id:row.code,code:row.code,description:row.description||row.name||row.code,itemClass:row.itemClass,uom:row.uom,standardCost:Number(row.standardCost||0),averageCost:Number(row.averageCost||0),defaultWarehouse:row.defaultWarehouse||'MAIN',defaultLocation:row.defaultLocation||'MAIN-A1',preferredVendor:row.preferredVendor||'',hasBom:!!effectiveBom(row.code),hasRouting:!!effectiveRouting(row.code)})),warehouses,locations:inventoryLocations,vendors:vendors.filter(v=>v.status!=='Inactive').map(v=>({id:v.id,name:v.name})),salesOrders:salesOrders.filter(o=>activeSoStatus(o.status)).map(o=>({id:o.id,orderNumber:o.orderNumber||o.id,customerId:o.customerId,customerName:o.customerName,status:o.status}))};}
  const userFrom=reqUser=>reqUser?.user?.id||reqUser?.id||reqUser?.email||'system';
  async function handle({method,pathname,query={},readBody,user}={}){
    if(!pathname?.startsWith('/api/manufacturing'))return null;const actor=userFrom(user),getBody=async()=>typeof readBody==='function'?await readBody():{};
    if(method==='GET'&&pathname==='/api/manufacturing/reference-data')return{status:200,body:referenceData()};
    if(method==='GET'&&pathname==='/api/manufacturing/overview')return{status:200,body:overview()};
    if(method==='GET'&&pathname==='/api/manufacturing/settings')return{status:200,body:settings};
    if(method==='PUT'&&pathname==='/api/manufacturing/settings'){Object.assign(settings,await getBody());audit('Manufacturing Settings','SETTINGS','Updated','',actor);return{status:200,body:settings};}
    if(method==='GET'&&pathname==='/api/manufacturing/work-centers')return{status:200,body:workCenters};
    if(method==='POST'&&pathname==='/api/manufacturing/work-centers')return{status:201,body:upsertWorkCenter(await getBody(),actor)};
    if(method==='GET'&&pathname==='/api/manufacturing/boms')return{status:200,body:boms};
    if(method==='POST'&&pathname==='/api/manufacturing/boms'){const input=await getBody(),existing=boms.find(row=>row.id===input.id),row=normalizeBom(input,existing);assertNoBomCycle(row);if(existing)Object.assign(existing,row);else boms.push(row);audit('BOM',row.id,existing?'Updated':'Created',`${row.itemId} rev ${row.revision}`,actor);return{status:existing?200:201,body:existing||row};}
    if(method==='GET'&&pathname==='/api/manufacturing/routings')return{status:200,body:routings};
    if(method==='POST'&&pathname==='/api/manufacturing/routings'){const input=await getBody(),existing=routings.find(row=>row.id===input.id),row=normalizeRouting(input,existing);if(existing)Object.assign(existing,row);else routings.push(row);audit('Routing',row.id,existing?'Updated':'Created',`${row.itemId} rev ${row.revision}`,actor);return{status:existing?200:201,body:existing||row};}
    if(method==='GET'&&pathname==='/api/manufacturing/orders')return{status:200,body:orders.map(serializeOrder)};
    if(method==='POST'&&pathname==='/api/manufacturing/orders')return{status:201,body:serializeOrder(createOrder(await getBody(),actor))};
    const orderMatch=pathname.match(/^\/api\/manufacturing\/orders\/([^/]+)(?:\/(release|issue-materials|report-operation|complete|close|cancel))?$/);if(orderMatch){const order=orders.find(row=>row.id===decodeURIComponent(orderMatch[1])||row.orderNumber===decodeURIComponent(orderMatch[1]));if(!order)return{status:404,body:{error:'Production order not found.'}};if(method==='GET'&&!orderMatch[2])return{status:200,body:serializeOrder(order)};if(method==='POST'){const action=orderMatch[2],input=await getBody();if(action==='release')releaseOrder(order,actor);else if(action==='issue-materials')issueMaterials(order,input,actor);else if(action==='report-operation')reportOperation(order,input,actor);else if(action==='complete')completeOrder(order,input,actor);else if(action==='close')closeOrder(order,actor);else if(action==='cancel')cancelOrder(order,actor);else return{status:405,body:{error:'Manufacturing order action is not supported.'}};return{status:200,body:serializeOrder(order)};}}
    if(method==='POST'&&pathname==='/api/manufacturing/mrp/run')return{status:200,body:runMrp(await getBody(),actor)};
    if(method==='GET'&&pathname==='/api/manufacturing/mrp/runs')return{status:200,body:mrpRuns};
    if(method==='GET'&&pathname==='/api/manufacturing/planned-orders')return{status:200,body:plannedOrders};
    const planMatch=pathname.match(/^\/api\/manufacturing\/planned-orders\/([^/]+)\/convert$/);if(method==='POST'&&planMatch){const plan=plannedOrders.find(row=>row.id===decodeURIComponent(planMatch[1]));if(!plan)return{status:404,body:{error:'Planned order not found.'}};return{status:200,body:convertPlan(plan,actor)};}
    if(method==='GET'&&pathname==='/api/manufacturing/quality/inspections')return{status:200,body:inspections};
    if(method==='POST'&&pathname==='/api/manufacturing/quality/inspections')return{status:201,body:createInspection(await getBody(),actor)};
    if(method==='GET'&&pathname==='/api/manufacturing/quality/nonconformances')return{status:200,body:nonconformances};
    const ncrMatch=pathname.match(/^\/api\/manufacturing\/quality\/nonconformances\/([^/]+)\/disposition$/);if(method==='POST'&&ncrMatch){const ncr=nonconformances.find(row=>row.id===decodeURIComponent(ncrMatch[1]));if(!ncr)return{status:404,body:{error:'Nonconformance not found.'}};return{status:200,body:dispositionNcr(ncr,await getBody(),actor)};}
    if(method==='GET'&&pathname==='/api/manufacturing/maintenance')return{status:200,body:maintenanceOrders};
    if(method==='POST'&&pathname==='/api/manufacturing/maintenance')return{status:201,body:createMaintenance(await getBody(),actor)};
    const maintenanceMatch=pathname.match(/^\/api\/manufacturing\/maintenance\/([^/]+)\/status$/);if(method==='POST'&&maintenanceMatch){const row=maintenanceOrders.find(x=>x.id===decodeURIComponent(maintenanceMatch[1]));if(!row)return{status:404,body:{error:'Maintenance work order not found.'}};const input=await getBody();return{status:200,body:setMaintenanceStatus(row,input.status,actor)};}
    if(method==='GET'&&pathname==='/api/manufacturing/reports/wip')return{status:200,body:wipReport()};
    if(method==='GET'&&pathname==='/api/manufacturing/reports/variance')return{status:200,body:varianceReport()};
    if(method==='GET'&&pathname==='/api/manufacturing/reports/material-shortages')return{status:200,body:shortageReport()};
    if(method==='GET'&&pathname==='/api/manufacturing/reports/capacity')return{status:200,body:capacityReport(query.horizonDays)};
    if(method==='GET'&&pathname==='/api/manufacturing/reports/production')return{status:200,body:productionReport()};
    if(method==='GET'&&pathname==='/api/manufacturing/audit')return{status:200,body:auditTrail};
    return{status:404,body:{error:'Manufacturing endpoint not found.'}};
  }

  return{handle,overview,runMrp,createOrder,releaseOrder,issueMaterials,reportOperation,completeOrder,closeOrder,createInspection,capacityReport,wipReport,varianceReport,shortageReport,productionReport,state:{settings,workCenters,boms,routings,orders,plannedOrders,mrpRuns,inspections,nonconformances,maintenanceOrders,auditTrail}};
}
